package treezor

// Currency is a string that contains the ISO 4217 currency code.
type Currency string

// All supported currency.
const (
	AED Currency = "AED" // United Arab Emirates Dirham
	AFN Currency = "AFN" // Afghan Afghani
	ALL Currency = "ALL" // Albanian Lek
	AMD Currency = "AMD" // Armenian Dram
	ANG Currency = "ANG" // Netherlands Antillean Gulden
	AOA Currency = "AOA" // Angolan Kwanza
	ARS Currency = "ARS" // Argentine Peso
	AUD Currency = "AUD" // Australian Dollar
	AWG Currency = "AWG" // Aruban Florin
	AZN Currency = "AZN" // Azerbaijani Manat
	BAM Currency = "BAM" // Bosnia & Herzegovina Convertible Mark
	BBD Currency = "BBD" // Barbadian Dollar
	BDT Currency = "BDT" // Bangladeshi Taka
	BGN Currency = "BGN" // Bulgarian Lev
	BIF Currency = "BIF" // Burundian Franc
	BMD Currency = "BMD" // Bermudian Dollar
	BND Currency = "BND" // Brunei Dollar
	BOB Currency = "BOB" // Bolivian Boliviano
	BRL Currency = "BRL" // Brazilian Real
	BSD Currency = "BSD" // Bahamian Dollar
	BTN Currency = "BTN" // Bhutanese Ngultrum
	BWP Currency = "BWP" // Botswana Pula
	BZD Currency = "BZD" // Belize Dollar
	CAD Currency = "CAD" // Canadian Dollar
	CDF Currency = "CDF" // Congolese Franc
	CHF Currency = "CHF" // Swiss Franc
	CLP Currency = "CLP" // Chilean Peso
	CNY Currency = "CNY" // Chinese Renminbi Yuan
	COP Currency = "COP" // Colombian Peso
	CRC Currency = "CRC" // Costa Rican Colón
	CVE Currency = "CVE" // Cape Verdean Escudo
	CZK Currency = "CZK" // Czech Koruna
	DJF Currency = "DJF" // Djiboutian Franc
	DKK Currency = "DKK" // Danish Krone
	DOP Currency = "DOP" // Dominican Peso
	DZD Currency = "DZD" // Algerian Dinar
	EEK Currency = "EEK" // Estonian Kroon
	EGP Currency = "EGP" // Egyptian Pound
	ERN Currency = "ERN" // Eritrean Nakfa
	ETB Currency = "ETB" // Ethiopian Birr
	EUR Currency = "EUR" // Euro
	FJD Currency = "FJD" // Fijian Dollar
	FKP Currency = "FKP" // Falkland Islands Pound
	GBP Currency = "GBP" // British Pound
	GEL Currency = "GEL" // Georgian Lari
	GIP Currency = "GIP" // Gibraltar Pound
	GMD Currency = "GMD" // Gambian Dalasi
	GNF Currency = "GNF" // Guinean Franc
	GTQ Currency = "GTQ" // Guatemalan Quetzal
	GYD Currency = "GYD" // Guyanese Dollar
	HKD Currency = "HKD" // Hong Kong Dollar
	HNL Currency = "HNL" // Honduran Lempira
	HRK Currency = "HRK" // Croatian Kuna
	HTG Currency = "HTG" // Haitian Gourde
	HUF Currency = "HUF" // Hungarian Forint
	IDR Currency = "IDR" // Indonesian Rupiah
	ILS Currency = "ILS" // Israeli New Sheqel
	INR Currency = "INR" // Indian Rupee
	ISK Currency = "ISK" // Icelandic Króna
	JMD Currency = "JMD" // Jamaican Dollar
	JPY Currency = "JPY" // Japanese Yen
	KES Currency = "KES" // Kenyan Shilling
	KGS Currency = "KGS" // Kyrgyzstani Som
	KHR Currency = "KHR" // Cambodian Riel
	KMF Currency = "KMF" // Comorian Franc
	KRW Currency = "KRW" // South Korean Won
	KYD Currency = "KYD" // Cayman Islands Dollar
	KZT Currency = "KZT" // Kazakhstani Tenge
	LAK Currency = "LAK" // Lao Kip
	LBP Currency = "LBP" // Lebanese Pound
	LKR Currency = "LKR" // Sri Lankan Rupee
	LRD Currency = "LRD" // Liberian Dollar
	LSL Currency = "LSL" // Lesotho Loti
	LTL Currency = "LTL" // Lithuanian Litas
	LVL Currency = "LVL" // Latvian Lats
	MAD Currency = "MAD" // Moroccan Dirham
	MDL Currency = "MDL" // Moldovan Leu
	MGA Currency = "MGA" // Malagasy Ariary
	MKD Currency = "MKD" // Macedonian Denar
	MNT Currency = "MNT" // Mongolian Tögrög
	MOP Currency = "MOP" // Macanese Pataca
	MRO Currency = "MRO" // Mauritanian Ouguiya
	MUR Currency = "MUR" // Mauritian Rupee
	MVR Currency = "MVR" // Maldivian Rufiyaa
	MWK Currency = "MWK" // Malawian Kwacha
	MXN Currency = "MXN" // Mexican Peso
	MYR Currency = "MYR" // Malaysian Ringgit
	MZN Currency = "MZN" // Mozambican Metical
	NAD Currency = "NAD" // Namibian Dollar
	NGN Currency = "NGN" // Nigerian Naira
	NIO Currency = "NIO" // Nicaraguan Córdoba
	NOK Currency = "NOK" // Norwegian Krone
	NPR Currency = "NPR" // Nepalese Rupee
	NZD Currency = "NZD" // New Zealand Dollar
	PAB Currency = "PAB" // Panamanian Balboa
	PEN Currency = "PEN" // Peruvian Nuevo Sol
	PGK Currency = "PGK" // Papua New Guinean Kina
	PHP Currency = "PHP" // Philippine Peso
	PKR Currency = "PKR" // Pakistani Rupee
	PLN Currency = "PLN" // Polish Złoty
	PYG Currency = "PYG" // Paraguayan Guaraní
	QAR Currency = "QAR" // Qatari Riyal
	RON Currency = "RON" // Romanian Leu
	RSD Currency = "RSD" // Serbian Dinar
	RUB Currency = "RUB" // Russian Ruble
	RWF Currency = "RWF" // Rwandan Franc
	SAR Currency = "SAR" // Saudi Riyal
	SBD Currency = "SBD" // Solomon Islands Dollar
	SCR Currency = "SCR" // Seychellois Rupee
	SEK Currency = "SEK" // Swedish Krona
	SGD Currency = "SGD" // Singapore Dollar
	SHP Currency = "SHP" // Saint Helenian Pound
	SLL Currency = "SLL" // Sierra Leonean Leone
	SOS Currency = "SOS" // Somali Shilling
	SRD Currency = "SRD" // Surinamese Dollar
	STD Currency = "STD" // São Tomé and Príncipe Dobra
	SVC Currency = "SVC" // Salvadoran Colón
	SZL Currency = "SZL" // Swazi Lilangeni
	THB Currency = "THB" // Thai Baht
	TJS Currency = "TJS" // Tajikistani Somoni
	TOP Currency = "TOP" // Tongan Paʻanga
	TRY Currency = "TRY" // Turkish Lira
	TTD Currency = "TTD" // Trinidad and Tobago Dollar
	TWD Currency = "TWD" // New Taiwan Dollar
	TZS Currency = "TZS" // Tanzanian Shilling
	UAH Currency = "UAH" // Ukrainian Hryvnia
	UGX Currency = "UGX" // Ugandan Shilling
	USD Currency = "USD" // United States Dollar
	UYU Currency = "UYU" // Uruguayan Peso
	UZS Currency = "UZS" // Uzbekistani Som
	VEF Currency = "VEF" // Venezuelan Bolívar
	VND Currency = "VND" // Vietnamese Đồng
	VUV Currency = "VUV" // Vanuatu Vatu
	WST Currency = "WST" // Samoan Tala
	XAF Currency = "XAF" // Central African Cfa Franc
	XCD Currency = "XCD" // East Caribbean Dollar
	XOF Currency = "XOF" // West African Cfa Franc
	XPF Currency = "XPF" // Cfp Franc
	YER Currency = "YER" // Yemeni Rial
	ZAR Currency = "ZAR" // South African Rand
	ZMW Currency = "ZMW" // Zambian Kwacha
)
