// Code generated by gen_accessors; DO NOT EDIT.

package treezor

import (
	"encoding/json"
	"net/http"
	"time"
)

// GetIdempotencyKey returns the IdempotencyKey field if it's non-nil, zero value otherwise.
func (a *Access) GetIdempotencyKey() string {
	if a != nil && a.IdempotencyKey != nil {
		return *a.IdempotencyKey
	}
	return ""
}

// GetUserID returns the UserID field if it's non-nil, zero value otherwise.
func (a *Access) GetUserID() string {
	if a != nil && a.UserID != nil {
		return *a.UserID
	}
	return ""
}

// GetUserIP returns the UserIP field if it's non-nil, zero value otherwise.
func (a *Access) GetUserIP() string {
	if a != nil && a.UserIP != nil {
		return *a.UserIP
	}
	return ""
}

// GetAuthorizations returns the Authorizations field if it's non-nil, zero value otherwise.
func (b *Balance) GetAuthorizations() float64 {
	if b != nil && b.Authorizations != nil {
		return *b.Authorizations
	}
	return 0.0
}

// GetAuthorizedBalance returns the AuthorizedBalance field if it's non-nil, zero value otherwise.
func (b *Balance) GetAuthorizedBalance() float64 {
	if b != nil && b.AuthorizedBalance != nil {
		return *b.AuthorizedBalance
	}
	return 0.0
}

// GetCalculationDate returns the CalculationDate field if it's non-nil, zero value otherwise.
func (b *Balance) GetCalculationDate() TimestampParis {
	if b != nil && b.CalculationDate != nil {
		return *b.CalculationDate
	}
	return TimestampParis{}
}

// GetCurrentBalance returns the CurrentBalance field if it's non-nil, zero value otherwise.
func (b *Balance) GetCurrentBalance() float64 {
	if b != nil && b.CurrentBalance != nil {
		return *b.CurrentBalance
	}
	return 0.0
}

// GetWalletID returns the WalletID field if it's non-nil, zero value otherwise.
func (b *Balance) GetWalletID() string {
	if b != nil && b.WalletID != nil {
		return *b.WalletID
	}
	return ""
}

// GetBalances returns the Balances field.
func (b *BalanceResponse) GetBalances() []*Balance {
	if b != nil {
		return b.Balances
	}
	return nil
}

// GetAddress returns the Address field if it's non-nil, zero value otherwise.
func (b *Beneficiary) GetAddress() string {
	if b != nil && b.Address != nil {
		return *b.Address
	}
	return ""
}

// GetBeneficiaryID returns the BeneficiaryID field if it's non-nil, zero value otherwise.
func (b *Beneficiary) GetBeneficiaryID() json.Number {
	if b != nil && b.BeneficiaryID != nil {
		return *b.BeneficiaryID
	}
	return json.Number("")
}

// GetBIC returns the BIC field if it's non-nil, zero value otherwise.
func (b *Beneficiary) GetBIC() string {
	if b != nil && b.BIC != nil {
		return *b.BIC
	}
	return ""
}

// GetEncryptedIBAN returns the EncryptedIBAN field if it's non-nil, zero value otherwise.
func (b *Beneficiary) GetEncryptedIBAN() string {
	if b != nil && b.EncryptedIBAN != nil {
		return *b.EncryptedIBAN
	}
	return ""
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (b *Beneficiary) GetName() string {
	if b != nil && b.Name != nil {
		return *b.Name
	}
	return ""
}

// GetNickName returns the NickName field if it's non-nil, zero value otherwise.
func (b *Beneficiary) GetNickName() string {
	if b != nil && b.NickName != nil {
		return *b.NickName
	}
	return ""
}

// GetSDDB2BWhitelist returns the SDDB2BWhitelist field.
func (b *Beneficiary) GetSDDB2BWhitelist() []*SDDB2BWhitelist {
	if b != nil {
		return b.SDDB2BWhitelist
	}
	return nil
}

// GetSDDCoreBlacklist returns the SDDCoreBlacklist field.
func (b *Beneficiary) GetSDDCoreBlacklist() []string {
	if b != nil {
		return b.SDDCoreBlacklist
	}
	return nil
}

// GetSDDCoreKnownUniqueMandateReference returns the SDDCoreKnownUniqueMandateReference field.
func (b *Beneficiary) GetSDDCoreKnownUniqueMandateReference() []string {
	if b != nil {
		return b.SDDCoreKnownUniqueMandateReference
	}
	return nil
}

// GetSEPACreditorIdentifier returns the SEPACreditorIdentifier field if it's non-nil, zero value otherwise.
func (b *Beneficiary) GetSEPACreditorIdentifier() string {
	if b != nil && b.SEPACreditorIdentifier != nil {
		return *b.SEPACreditorIdentifier
	}
	return ""
}

// GetTag returns the Tag field if it's non-nil, zero value otherwise.
func (b *Beneficiary) GetTag() string {
	if b != nil && b.Tag != nil {
		return *b.Tag
	}
	return ""
}

// GetUsableForSCT returns the UsableForSCT field if it's non-nil, zero value otherwise.
func (b *Beneficiary) GetUsableForSCT() bool {
	if b != nil && b.UsableForSCT != nil {
		return *b.UsableForSCT
	}
	return false
}

// GetUserID returns the UserID field if it's non-nil, zero value otherwise.
func (b *Beneficiary) GetUserID() json.Number {
	if b != nil && b.UserID != nil {
		return *b.UserID
	}
	return json.Number("")
}

// GetAddress returns the Address field if it's non-nil, zero value otherwise.
func (b *BeneficiaryRequest) GetAddress() string {
	if b != nil && b.Address != nil {
		return *b.Address
	}
	return ""
}

// GetBeneficiaryID returns the BeneficiaryID field if it's non-nil, zero value otherwise.
func (b *BeneficiaryRequest) GetBeneficiaryID() string {
	if b != nil && b.BeneficiaryID != nil {
		return *b.BeneficiaryID
	}
	return ""
}

// GetBIC returns the BIC field if it's non-nil, zero value otherwise.
func (b *BeneficiaryRequest) GetBIC() string {
	if b != nil && b.BIC != nil {
		return *b.BIC
	}
	return ""
}

// GetIBAN returns the IBAN field if it's non-nil, zero value otherwise.
func (b *BeneficiaryRequest) GetIBAN() string {
	if b != nil && b.IBAN != nil {
		return *b.IBAN
	}
	return ""
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (b *BeneficiaryRequest) GetName() string {
	if b != nil && b.Name != nil {
		return *b.Name
	}
	return ""
}

// GetNickName returns the NickName field if it's non-nil, zero value otherwise.
func (b *BeneficiaryRequest) GetNickName() string {
	if b != nil && b.NickName != nil {
		return *b.NickName
	}
	return ""
}

// GetSDDB2BWhitelist returns the SDDB2BWhitelist field.
func (b *BeneficiaryRequest) GetSDDB2BWhitelist() []*SDDB2BWhitelist {
	if b != nil {
		return b.SDDB2BWhitelist
	}
	return nil
}

// GetSDDCoreBlacklist returns the SDDCoreBlacklist field if it's non-nil, zero value otherwise.
func (b *BeneficiaryRequest) GetSDDCoreBlacklist() []string {
	if b != nil && b.SDDCoreBlacklist != nil {
		return *b.SDDCoreBlacklist
	}
	return nil
}

// GetSDDCoreKnownUniqueMandateReference returns the SDDCoreKnownUniqueMandateReference field if it's non-nil, zero value otherwise.
func (b *BeneficiaryRequest) GetSDDCoreKnownUniqueMandateReference() []string {
	if b != nil && b.SDDCoreKnownUniqueMandateReference != nil {
		return *b.SDDCoreKnownUniqueMandateReference
	}
	return nil
}

// GetSEPACreditorIdentifier returns the SEPACreditorIdentifier field if it's non-nil, zero value otherwise.
func (b *BeneficiaryRequest) GetSEPACreditorIdentifier() string {
	if b != nil && b.SEPACreditorIdentifier != nil {
		return *b.SEPACreditorIdentifier
	}
	return ""
}

// GetTag returns the Tag field if it's non-nil, zero value otherwise.
func (b *BeneficiaryRequest) GetTag() string {
	if b != nil && b.Tag != nil {
		return *b.Tag
	}
	return ""
}

// GetUsableForSCT returns the UsableForSCT field if it's non-nil, zero value otherwise.
func (b *BeneficiaryRequest) GetUsableForSCT() bool {
	if b != nil && b.UsableForSCT != nil {
		return *b.UsableForSCT
	}
	return false
}

// GetUserID returns the UserID field if it's non-nil, zero value otherwise.
func (b *BeneficiaryRequest) GetUserID() string {
	if b != nil && b.UserID != nil {
		return *b.UserID
	}
	return ""
}

// GetBeneficiaries returns the Beneficiaries field.
func (b *BeneficiaryResponse) GetBeneficiaries() []*Beneficiary {
	if b != nil {
		return b.Beneficiaries
	}
	return nil
}

// GetCardDesign returns the CardDesign field if it's non-nil, zero value otherwise.
func (c *Card) GetCardDesign() string {
	if c != nil && c.CardDesign != nil {
		return *c.CardDesign
	}
	return ""
}

// GetCardID returns the CardID field if it's non-nil, zero value otherwise.
func (c *Card) GetCardID() string {
	if c != nil && c.CardID != nil {
		return *c.CardID
	}
	return ""
}

// GetCardPrint returns the CardPrint field if it's non-nil, zero value otherwise.
func (c *Card) GetCardPrint() string {
	if c != nil && c.CardPrint != nil {
		return *c.CardPrint
	}
	return ""
}

// GetCardTag returns the CardTag field if it's non-nil, zero value otherwise.
func (c *Card) GetCardTag() string {
	if c != nil && c.CardTag != nil {
		return *c.CardTag
	}
	return ""
}

// GetCountryCode returns the CountryCode field if it's non-nil, zero value otherwise.
func (c *Card) GetCountryCode() string {
	if c != nil && c.CountryCode != nil {
		return *c.CountryCode
	}
	return ""
}

// GetCreatedBy returns the CreatedBy field if it's non-nil, zero value otherwise.
func (c *Card) GetCreatedBy() string {
	if c != nil && c.CreatedBy != nil {
		return *c.CreatedBy
	}
	return ""
}

// GetCreatedDate returns the CreatedDate field if it's non-nil, zero value otherwise.
func (c *Card) GetCreatedDate() TimestampLondon {
	if c != nil && c.CreatedDate != nil {
		return *c.CreatedDate
	}
	return TimestampLondon{}
}

// GetCVV returns the CVV field if it's non-nil, zero value otherwise.
func (c *Card) GetCVV() string {
	if c != nil && c.CVV != nil {
		return *c.CVV
	}
	return ""
}

// GetDeliveryAddress1 returns the DeliveryAddress1 field if it's non-nil, zero value otherwise.
func (c *Card) GetDeliveryAddress1() string {
	if c != nil && c.DeliveryAddress1 != nil {
		return *c.DeliveryAddress1
	}
	return ""
}

// GetDeliveryAddress2 returns the DeliveryAddress2 field if it's non-nil, zero value otherwise.
func (c *Card) GetDeliveryAddress2() string {
	if c != nil && c.DeliveryAddress2 != nil {
		return *c.DeliveryAddress2
	}
	return ""
}

// GetDeliveryAddress3 returns the DeliveryAddress3 field if it's non-nil, zero value otherwise.
func (c *Card) GetDeliveryAddress3() string {
	if c != nil && c.DeliveryAddress3 != nil {
		return *c.DeliveryAddress3
	}
	return ""
}

// GetDeliveryCity returns the DeliveryCity field if it's non-nil, zero value otherwise.
func (c *Card) GetDeliveryCity() string {
	if c != nil && c.DeliveryCity != nil {
		return *c.DeliveryCity
	}
	return ""
}

// GetDeliveryCountry returns the DeliveryCountry field if it's non-nil, zero value otherwise.
func (c *Card) GetDeliveryCountry() string {
	if c != nil && c.DeliveryCountry != nil {
		return *c.DeliveryCountry
	}
	return ""
}

// GetDeliveryFirstname returns the DeliveryFirstname field if it's non-nil, zero value otherwise.
func (c *Card) GetDeliveryFirstname() string {
	if c != nil && c.DeliveryFirstname != nil {
		return *c.DeliveryFirstname
	}
	return ""
}

// GetDeliveryLastname returns the DeliveryLastname field if it's non-nil, zero value otherwise.
func (c *Card) GetDeliveryLastname() string {
	if c != nil && c.DeliveryLastname != nil {
		return *c.DeliveryLastname
	}
	return ""
}

// GetDeliveryPostcode returns the DeliveryPostcode field if it's non-nil, zero value otherwise.
func (c *Card) GetDeliveryPostcode() string {
	if c != nil && c.DeliveryPostcode != nil {
		return *c.DeliveryPostcode
	}
	return ""
}

// GetDeliveryTitle returns the DeliveryTitle field if it's non-nil, zero value otherwise.
func (c *Card) GetDeliveryTitle() string {
	if c != nil && c.DeliveryTitle != nil {
		return *c.DeliveryTitle
	}
	return ""
}

// GetEmbossedName returns the EmbossedName field if it's non-nil, zero value otherwise.
func (c *Card) GetEmbossedName() string {
	if c != nil && c.EmbossedName != nil {
		return *c.EmbossedName
	}
	return ""
}

// GetEndDate returns the EndDate field if it's non-nil, zero value otherwise.
func (c *Card) GetEndDate() Date {
	if c != nil && c.EndDate != nil {
		return *c.EndDate
	}
	return Date{}
}

// GetExpiryDate returns the ExpiryDate field if it's non-nil, zero value otherwise.
func (c *Card) GetExpiryDate() Date {
	if c != nil && c.ExpiryDate != nil {
		return *c.ExpiryDate
	}
	return Date{}
}

// GetIsLive returns the IsLive field if it's non-nil, zero value otherwise.
func (c *Card) GetIsLive() int64 {
	if c != nil && c.IsLive != nil {
		return *c.IsLive
	}
	return 0
}

// GetIsPhysical returns the IsPhysical field if it's non-nil, zero value otherwise.
func (c *Card) GetIsPhysical() int64 {
	if c != nil && c.IsPhysical != nil {
		return *c.IsPhysical
	}
	return 0
}

// GetLang returns the Lang field if it's non-nil, zero value otherwise.
func (c *Card) GetLang() string {
	if c != nil && c.Lang != nil {
		return *c.Lang
	}
	return ""
}

// GetLimitATMAll returns the LimitATMAll field if it's non-nil, zero value otherwise.
func (c *Card) GetLimitATMAll() int64 {
	if c != nil && c.LimitATMAll != nil {
		return *c.LimitATMAll
	}
	return 0
}

// GetLimitATMDay returns the LimitATMDay field if it's non-nil, zero value otherwise.
func (c *Card) GetLimitATMDay() int64 {
	if c != nil && c.LimitATMDay != nil {
		return *c.LimitATMDay
	}
	return 0
}

// GetLimitATMMonth returns the LimitATMMonth field if it's non-nil, zero value otherwise.
func (c *Card) GetLimitATMMonth() int64 {
	if c != nil && c.LimitATMMonth != nil {
		return *c.LimitATMMonth
	}
	return 0
}

// GetLimitATMWeek returns the LimitATMWeek field if it's non-nil, zero value otherwise.
func (c *Card) GetLimitATMWeek() int64 {
	if c != nil && c.LimitATMWeek != nil {
		return *c.LimitATMWeek
	}
	return 0
}

// GetLimitATMYear returns the LimitATMYear field if it's non-nil, zero value otherwise.
func (c *Card) GetLimitATMYear() int64 {
	if c != nil && c.LimitATMYear != nil {
		return *c.LimitATMYear
	}
	return 0
}

// GetLimitPaymentAll returns the LimitPaymentAll field if it's non-nil, zero value otherwise.
func (c *Card) GetLimitPaymentAll() int64 {
	if c != nil && c.LimitPaymentAll != nil {
		return *c.LimitPaymentAll
	}
	return 0
}

// GetLimitPaymentDay returns the LimitPaymentDay field if it's non-nil, zero value otherwise.
func (c *Card) GetLimitPaymentDay() int64 {
	if c != nil && c.LimitPaymentDay != nil {
		return *c.LimitPaymentDay
	}
	return 0
}

// GetLimitPaymentMonth returns the LimitPaymentMonth field if it's non-nil, zero value otherwise.
func (c *Card) GetLimitPaymentMonth() int64 {
	if c != nil && c.LimitPaymentMonth != nil {
		return *c.LimitPaymentMonth
	}
	return 0
}

// GetLimitPaymentWeek returns the LimitPaymentWeek field if it's non-nil, zero value otherwise.
func (c *Card) GetLimitPaymentWeek() int64 {
	if c != nil && c.LimitPaymentWeek != nil {
		return *c.LimitPaymentWeek
	}
	return 0
}

// GetLimitPaymentYear returns the LimitPaymentYear field if it's non-nil, zero value otherwise.
func (c *Card) GetLimitPaymentYear() int64 {
	if c != nil && c.LimitPaymentYear != nil {
		return *c.LimitPaymentYear
	}
	return 0
}

// GetLimitsGroup returns the LimitsGroup field if it's non-nil, zero value otherwise.
func (c *Card) GetLimitsGroup() string {
	if c != nil && c.LimitsGroup != nil {
		return *c.LimitsGroup
	}
	return ""
}

// GetLockStatus returns the LockStatus field if it's non-nil, zero value otherwise.
func (c *Card) GetLockStatus() int64 {
	if c != nil && c.LockStatus != nil {
		return *c.LockStatus
	}
	return 0
}

// GetMaskedPan returns the MaskedPan field if it's non-nil, zero value otherwise.
func (c *Card) GetMaskedPan() string {
	if c != nil && c.MaskedPan != nil {
		return *c.MaskedPan
	}
	return ""
}

// GetMccRestrictionGroupID returns the MccRestrictionGroupID field if it's non-nil, zero value otherwise.
func (c *Card) GetMccRestrictionGroupID() string {
	if c != nil && c.MccRestrictionGroupID != nil {
		return *c.MccRestrictionGroupID
	}
	return ""
}

// GetMerchantRestrictionGroupID returns the MerchantRestrictionGroupID field if it's non-nil, zero value otherwise.
func (c *Card) GetMerchantRestrictionGroupID() string {
	if c != nil && c.MerchantRestrictionGroupID != nil {
		return *c.MerchantRestrictionGroupID
	}
	return ""
}

// GetMobileSent returns the MobileSent field if it's non-nil, zero value otherwise.
func (c *Card) GetMobileSent() string {
	if c != nil && c.MobileSent != nil {
		return *c.MobileSent
	}
	return ""
}

// GetModifiedBy returns the ModifiedBy field if it's non-nil, zero value otherwise.
func (c *Card) GetModifiedBy() string {
	if c != nil && c.ModifiedBy != nil {
		return *c.ModifiedBy
	}
	return ""
}

// GetModifiedDate returns the ModifiedDate field if it's non-nil, zero value otherwise.
func (c *Card) GetModifiedDate() TimestampLondon {
	if c != nil && c.ModifiedDate != nil {
		return *c.ModifiedDate
	}
	return TimestampLondon{}
}

// GetOptionATM returns the OptionATM field if it's non-nil, zero value otherwise.
func (c *Card) GetOptionATM() int64 {
	if c != nil && c.OptionATM != nil {
		return *c.OptionATM
	}
	return 0
}

// GetOptionForeign returns the OptionForeign field if it's non-nil, zero value otherwise.
func (c *Card) GetOptionForeign() int64 {
	if c != nil && c.OptionForeign != nil {
		return *c.OptionForeign
	}
	return 0
}

// GetOptionNFC returns the OptionNFC field if it's non-nil, zero value otherwise.
func (c *Card) GetOptionNFC() int64 {
	if c != nil && c.OptionNFC != nil {
		return *c.OptionNFC
	}
	return 0
}

// GetOptionOnline returns the OptionOnline field if it's non-nil, zero value otherwise.
func (c *Card) GetOptionOnline() int64 {
	if c != nil && c.OptionOnline != nil {
		return *c.OptionOnline
	}
	return 0
}

// GetPermsGroup returns the PermsGroup field if it's non-nil, zero value otherwise.
func (c *Card) GetPermsGroup() string {
	if c != nil && c.PermsGroup != nil {
		return *c.PermsGroup
	}
	return ""
}

// GetPIN returns the PIN field if it's non-nil, zero value otherwise.
func (c *Card) GetPIN() string {
	if c != nil && c.PIN != nil {
		return *c.PIN
	}
	return ""
}

// GetPINTryExceeds returns the PINTryExceeds field if it's non-nil, zero value otherwise.
func (c *Card) GetPINTryExceeds() int64 {
	if c != nil && c.PINTryExceeds != nil {
		return *c.PINTryExceeds
	}
	return 0
}

// GetPublicToken returns the PublicToken field if it's non-nil, zero value otherwise.
func (c *Card) GetPublicToken() string {
	if c != nil && c.PublicToken != nil {
		return *c.PublicToken
	}
	return ""
}

// GetStartDate returns the StartDate field if it's non-nil, zero value otherwise.
func (c *Card) GetStartDate() Date {
	if c != nil && c.StartDate != nil {
		return *c.StartDate
	}
	return Date{}
}

// GetStatusCode returns the StatusCode field if it's non-nil, zero value otherwise.
func (c *Card) GetStatusCode() string {
	if c != nil && c.StatusCode != nil {
		return *c.StatusCode
	}
	return ""
}

// GetTotalATMAll returns the TotalATMAll field if it's non-nil, zero value otherwise.
func (c *Card) GetTotalATMAll() float64 {
	if c != nil && c.TotalATMAll != nil {
		return *c.TotalATMAll
	}
	return 0.0
}

// GetTotalATMDay returns the TotalATMDay field if it's non-nil, zero value otherwise.
func (c *Card) GetTotalATMDay() float64 {
	if c != nil && c.TotalATMDay != nil {
		return *c.TotalATMDay
	}
	return 0.0
}

// GetTotalATMMonth returns the TotalATMMonth field if it's non-nil, zero value otherwise.
func (c *Card) GetTotalATMMonth() float64 {
	if c != nil && c.TotalATMMonth != nil {
		return *c.TotalATMMonth
	}
	return 0.0
}

// GetTotalATMWeek returns the TotalATMWeek field if it's non-nil, zero value otherwise.
func (c *Card) GetTotalATMWeek() float64 {
	if c != nil && c.TotalATMWeek != nil {
		return *c.TotalATMWeek
	}
	return 0.0
}

// GetTotalATMYear returns the TotalATMYear field if it's non-nil, zero value otherwise.
func (c *Card) GetTotalATMYear() float64 {
	if c != nil && c.TotalATMYear != nil {
		return *c.TotalATMYear
	}
	return 0.0
}

// GetTotalPaymentAll returns the TotalPaymentAll field if it's non-nil, zero value otherwise.
func (c *Card) GetTotalPaymentAll() float64 {
	if c != nil && c.TotalPaymentAll != nil {
		return *c.TotalPaymentAll
	}
	return 0.0
}

// GetTotalPaymentDay returns the TotalPaymentDay field if it's non-nil, zero value otherwise.
func (c *Card) GetTotalPaymentDay() float64 {
	if c != nil && c.TotalPaymentDay != nil {
		return *c.TotalPaymentDay
	}
	return 0.0
}

// GetTotalPaymentMonth returns the TotalPaymentMonth field if it's non-nil, zero value otherwise.
func (c *Card) GetTotalPaymentMonth() float64 {
	if c != nil && c.TotalPaymentMonth != nil {
		return *c.TotalPaymentMonth
	}
	return 0.0
}

// GetTotalPaymentWeek returns the TotalPaymentWeek field if it's non-nil, zero value otherwise.
func (c *Card) GetTotalPaymentWeek() float64 {
	if c != nil && c.TotalPaymentWeek != nil {
		return *c.TotalPaymentWeek
	}
	return 0.0
}

// GetTotalPaymentYear returns the TotalPaymentYear field if it's non-nil, zero value otherwise.
func (c *Card) GetTotalPaymentYear() float64 {
	if c != nil && c.TotalPaymentYear != nil {
		return *c.TotalPaymentYear
	}
	return 0.0
}

// GetTotalRows returns the TotalRows field if it's non-nil, zero value otherwise.
func (c *Card) GetTotalRows() int64 {
	if c != nil && c.TotalRows != nil {
		return *c.TotalRows
	}
	return 0
}

// GetUserID returns the UserID field if it's non-nil, zero value otherwise.
func (c *Card) GetUserID() string {
	if c != nil && c.UserID != nil {
		return *c.UserID
	}
	return ""
}

// GetVirtualConverted returns the VirtualConverted field if it's non-nil, zero value otherwise.
func (c *Card) GetVirtualConverted() int64 {
	if c != nil && c.VirtualConverted != nil {
		return *c.VirtualConverted
	}
	return 0
}

// GetWalletCardtransactionID returns the WalletCardtransactionID field if it's non-nil, zero value otherwise.
func (c *Card) GetWalletCardtransactionID() string {
	if c != nil && c.WalletCardtransactionID != nil {
		return *c.WalletCardtransactionID
	}
	return ""
}

// GetWalletID returns the WalletID field if it's non-nil, zero value otherwise.
func (c *Card) GetWalletID() string {
	if c != nil && c.WalletID != nil {
		return *c.WalletID
	}
	return ""
}

// GetCardID returns the CardID field if it's non-nil, zero value otherwise.
func (c *Card3DS) GetCardID() string {
	if c != nil && c.CardID != nil {
		return *c.CardID
	}
	return ""
}

// GetCardID returns the CardID field if it's non-nil, zero value otherwise.
func (c *CardImage) GetCardID() string {
	if c != nil && c.CardID != nil {
		return *c.CardID
	}
	return ""
}

// GetFile returns the File field if it's non-nil, zero value otherwise.
func (c *CardImage) GetFile() string {
	if c != nil && c.File != nil {
		return *c.File
	}
	return ""
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (c *CardImage) GetID() string {
	if c != nil && c.ID != nil {
		return *c.ID
	}
	return ""
}

// GetCardImages returns the CardImages field.
func (c *CardImagesResponse) GetCardImages() []*CardImage {
	if c != nil {
		return c.CardImages
	}
	return nil
}

// GetCards returns the Cards field.
func (c *CardResponse) GetCards() []*Card {
	if c != nil {
		return c.Cards
	}
	return nil
}

// GetAuthorizationIssuerID returns the AuthorizationIssuerID field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetAuthorizationIssuerID() string {
	if c != nil && c.AuthorizationIssuerID != nil {
		return *c.AuthorizationIssuerID
	}
	return ""
}

// GetAuthorizationIssuerTime returns the AuthorizationIssuerTime field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetAuthorizationIssuerTime() TimestampLondon {
	if c != nil && c.AuthorizationIssuerTime != nil {
		return *c.AuthorizationIssuerTime
	}
	return TimestampLondon{}
}

// GetAuthorizationMti returns the AuthorizationMti field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetAuthorizationMti() string {
	if c != nil && c.AuthorizationMti != nil {
		return *c.AuthorizationMti
	}
	return ""
}

// GetAuthorizationNote returns the AuthorizationNote field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetAuthorizationNote() string {
	if c != nil && c.AuthorizationNote != nil {
		return *c.AuthorizationNote
	}
	return ""
}

// GetAuthorizationResponseCode returns the AuthorizationResponseCode field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetAuthorizationResponseCode() string {
	if c != nil && c.AuthorizationResponseCode != nil {
		return *c.AuthorizationResponseCode
	}
	return ""
}

// GetAuthorizedBalance returns the AuthorizedBalance field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetAuthorizedBalance() float64 {
	if c != nil && c.AuthorizedBalance != nil {
		return *c.AuthorizedBalance
	}
	return 0.0
}

// GetCardID returns the CardID field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetCardID() string {
	if c != nil && c.CardID != nil {
		return *c.CardID
	}
	return ""
}

// GetCardTransactionID returns the CardTransactionID field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetCardTransactionID() string {
	if c != nil && c.CardTransactionID != nil {
		return *c.CardTransactionID
	}
	return ""
}

// GetFees returns the Fees field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetFees() float64 {
	if c != nil && c.Fees != nil {
		return *c.Fees
	}
	return 0.0
}

// GetIs3DS returns the Is3DS field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetIs3DS() string {
	if c != nil && c.Is3DS != nil {
		return *c.Is3DS
	}
	return ""
}

// GetLimitATMAll returns the LimitATMAll field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetLimitATMAll() int64 {
	if c != nil && c.LimitATMAll != nil {
		return *c.LimitATMAll
	}
	return 0
}

// GetLimitATMDay returns the LimitATMDay field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetLimitATMDay() int64 {
	if c != nil && c.LimitATMDay != nil {
		return *c.LimitATMDay
	}
	return 0
}

// GetLimitATMMonth returns the LimitATMMonth field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetLimitATMMonth() int64 {
	if c != nil && c.LimitATMMonth != nil {
		return *c.LimitATMMonth
	}
	return 0
}

// GetLimitATMWeek returns the LimitATMWeek field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetLimitATMWeek() int64 {
	if c != nil && c.LimitATMWeek != nil {
		return *c.LimitATMWeek
	}
	return 0
}

// GetLimitATMYear returns the LimitATMYear field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetLimitATMYear() int64 {
	if c != nil && c.LimitATMYear != nil {
		return *c.LimitATMYear
	}
	return 0
}

// GetLimitPaymentAll returns the LimitPaymentAll field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetLimitPaymentAll() int64 {
	if c != nil && c.LimitPaymentAll != nil {
		return *c.LimitPaymentAll
	}
	return 0
}

// GetLimitPaymentDay returns the LimitPaymentDay field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetLimitPaymentDay() int64 {
	if c != nil && c.LimitPaymentDay != nil {
		return *c.LimitPaymentDay
	}
	return 0
}

// GetLimitPaymentMonth returns the LimitPaymentMonth field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetLimitPaymentMonth() int64 {
	if c != nil && c.LimitPaymentMonth != nil {
		return *c.LimitPaymentMonth
	}
	return 0
}

// GetLimitPaymentWeek returns the LimitPaymentWeek field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetLimitPaymentWeek() int64 {
	if c != nil && c.LimitPaymentWeek != nil {
		return *c.LimitPaymentWeek
	}
	return 0
}

// GetLimitPaymentYear returns the LimitPaymentYear field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetLimitPaymentYear() int64 {
	if c != nil && c.LimitPaymentYear != nil {
		return *c.LimitPaymentYear
	}
	return 0
}

// GetMccCode returns the MccCode field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetMccCode() string {
	if c != nil && c.MccCode != nil {
		return *c.MccCode
	}
	return ""
}

// GetMerchantCity returns the MerchantCity field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetMerchantCity() string {
	if c != nil && c.MerchantCity != nil {
		return *c.MerchantCity
	}
	return ""
}

// GetMerchantCountry returns the MerchantCountry field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetMerchantCountry() string {
	if c != nil && c.MerchantCountry != nil {
		return *c.MerchantCountry
	}
	return ""
}

// GetMerchantID returns the MerchantID field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetMerchantID() string {
	if c != nil && c.MerchantID != nil {
		return *c.MerchantID
	}
	return ""
}

// GetMerchantName returns the MerchantName field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetMerchantName() string {
	if c != nil && c.MerchantName != nil {
		return *c.MerchantName
	}
	return ""
}

// GetPanEntryMethod returns the PanEntryMethod field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetPanEntryMethod() string {
	if c != nil && c.PanEntryMethod != nil {
		return *c.PanEntryMethod
	}
	return ""
}

// GetPaymentAmount returns the PaymentAmount field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetPaymentAmount() float64 {
	if c != nil && c.PaymentAmount != nil {
		return *c.PaymentAmount
	}
	return 0.0
}

// GetPaymentCountry returns the PaymentCountry field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetPaymentCountry() string {
	if c != nil && c.PaymentCountry != nil {
		return *c.PaymentCountry
	}
	return ""
}

// GetPaymentCurrency returns the PaymentCurrency field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetPaymentCurrency() string {
	if c != nil && c.PaymentCurrency != nil {
		return *c.PaymentCurrency
	}
	return ""
}

// GetPaymentID returns the PaymentID field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetPaymentID() string {
	if c != nil && c.PaymentID != nil {
		return *c.PaymentID
	}
	return ""
}

// GetPaymentLocalAmount returns the PaymentLocalAmount field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetPaymentLocalAmount() float64 {
	if c != nil && c.PaymentLocalAmount != nil {
		return *c.PaymentLocalAmount
	}
	return 0.0
}

// GetPaymentLocalTime returns the PaymentLocalTime field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetPaymentLocalTime() string {
	if c != nil && c.PaymentLocalTime != nil {
		return *c.PaymentLocalTime
	}
	return ""
}

// GetPaymentStatus returns the PaymentStatus field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetPaymentStatus() string {
	if c != nil && c.PaymentStatus != nil {
		return *c.PaymentStatus
	}
	return ""
}

// GetPosCardholderPresence returns the PosCardholderPresence field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetPosCardholderPresence() string {
	if c != nil && c.PosCardholderPresence != nil {
		return *c.PosCardholderPresence
	}
	return ""
}

// GetPosCardPresence returns the PosCardPresence field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetPosCardPresence() string {
	if c != nil && c.PosCardPresence != nil {
		return *c.PosCardPresence
	}
	return ""
}

// GetPosCountry returns the PosCountry field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetPosCountry() string {
	if c != nil && c.PosCountry != nil {
		return *c.PosCountry
	}
	return ""
}

// GetPosPostcode returns the PosPostcode field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetPosPostcode() string {
	if c != nil && c.PosPostcode != nil {
		return *c.PosPostcode
	}
	return ""
}

// GetPosTerminalID returns the PosTerminalID field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetPosTerminalID() string {
	if c != nil && c.PosTerminalID != nil {
		return *c.PosTerminalID
	}
	return ""
}

// GetPublicToken returns the PublicToken field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetPublicToken() string {
	if c != nil && c.PublicToken != nil {
		return *c.PublicToken
	}
	return ""
}

// GetTotalLimitATMAll returns the TotalLimitATMAll field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetTotalLimitATMAll() float64 {
	if c != nil && c.TotalLimitATMAll != nil {
		return *c.TotalLimitATMAll
	}
	return 0.0
}

// GetTotalLimitATMDay returns the TotalLimitATMDay field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetTotalLimitATMDay() float64 {
	if c != nil && c.TotalLimitATMDay != nil {
		return *c.TotalLimitATMDay
	}
	return 0.0
}

// GetTotalLimitATMMonth returns the TotalLimitATMMonth field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetTotalLimitATMMonth() float64 {
	if c != nil && c.TotalLimitATMMonth != nil {
		return *c.TotalLimitATMMonth
	}
	return 0.0
}

// GetTotalLimitATMWeek returns the TotalLimitATMWeek field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetTotalLimitATMWeek() float64 {
	if c != nil && c.TotalLimitATMWeek != nil {
		return *c.TotalLimitATMWeek
	}
	return 0.0
}

// GetTotalLimitATMYear returns the TotalLimitATMYear field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetTotalLimitATMYear() float64 {
	if c != nil && c.TotalLimitATMYear != nil {
		return *c.TotalLimitATMYear
	}
	return 0.0
}

// GetTotalLimitPaymentAll returns the TotalLimitPaymentAll field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetTotalLimitPaymentAll() float64 {
	if c != nil && c.TotalLimitPaymentAll != nil {
		return *c.TotalLimitPaymentAll
	}
	return 0.0
}

// GetTotalLimitPaymentDay returns the TotalLimitPaymentDay field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetTotalLimitPaymentDay() float64 {
	if c != nil && c.TotalLimitPaymentDay != nil {
		return *c.TotalLimitPaymentDay
	}
	return 0.0
}

// GetTotalLimitPaymentMonth returns the TotalLimitPaymentMonth field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetTotalLimitPaymentMonth() float64 {
	if c != nil && c.TotalLimitPaymentMonth != nil {
		return *c.TotalLimitPaymentMonth
	}
	return 0.0
}

// GetTotalLimitPaymentWeek returns the TotalLimitPaymentWeek field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetTotalLimitPaymentWeek() float64 {
	if c != nil && c.TotalLimitPaymentWeek != nil {
		return *c.TotalLimitPaymentWeek
	}
	return 0.0
}

// GetTotalLimitPaymentYear returns the TotalLimitPaymentYear field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetTotalLimitPaymentYear() float64 {
	if c != nil && c.TotalLimitPaymentYear != nil {
		return *c.TotalLimitPaymentYear
	}
	return 0.0
}

// GetWalletCurrency returns the WalletCurrency field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetWalletCurrency() string {
	if c != nil && c.WalletCurrency != nil {
		return *c.WalletCurrency
	}
	return ""
}

// GetWalletID returns the WalletID field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetWalletID() string {
	if c != nil && c.WalletID != nil {
		return *c.WalletID
	}
	return ""
}

// GetCardTransactions returns the CardTransactions field.
func (c *CardTransactionResponse) GetCardTransactions() []*CardTransaction {
	if c != nil {
		return c.CardTransactions
	}
	return nil
}

// GetClientID returns the ClientID field if it's non-nil, zero value otherwise.
func (d *Document) GetClientID() string {
	if d != nil && d.ClientID != nil {
		return *d.ClientID
	}
	return ""
}

// GetCodeStatus returns the CodeStatus field if it's non-nil, zero value otherwise.
func (d *Document) GetCodeStatus() string {
	if d != nil && d.CodeStatus != nil {
		return *d.CodeStatus
	}
	return ""
}

// GetCreatedDate returns the CreatedDate field if it's non-nil, zero value otherwise.
func (d *Document) GetCreatedDate() string {
	if d != nil && d.CreatedDate != nil {
		return *d.CreatedDate
	}
	return ""
}

// GetDocumentID returns the DocumentID field if it's non-nil, zero value otherwise.
func (d *Document) GetDocumentID() string {
	if d != nil && d.DocumentID != nil {
		return *d.DocumentID
	}
	return ""
}

// GetDocumentStatus returns the DocumentStatus field if it's non-nil, zero value otherwise.
func (d *Document) GetDocumentStatus() string {
	if d != nil && d.DocumentStatus != nil {
		return *d.DocumentStatus
	}
	return ""
}

// GetDocumentType returns the DocumentType field if it's non-nil, zero value otherwise.
func (d *Document) GetDocumentType() string {
	if d != nil && d.DocumentType != nil {
		return *d.DocumentType
	}
	return ""
}

// GetFilename returns the Filename field if it's non-nil, zero value otherwise.
func (d *Document) GetFilename() string {
	if d != nil && d.Filename != nil {
		return *d.Filename
	}
	return ""
}

// GetFileSize returns the FileSize field if it's non-nil, zero value otherwise.
func (d *Document) GetFileSize() int64 {
	if d != nil && d.FileSize != nil {
		return *d.FileSize
	}
	return 0
}

// GetInformationStatus returns the InformationStatus field if it's non-nil, zero value otherwise.
func (d *Document) GetInformationStatus() string {
	if d != nil && d.InformationStatus != nil {
		return *d.InformationStatus
	}
	return ""
}

// GetModifiedDate returns the ModifiedDate field if it's non-nil, zero value otherwise.
func (d *Document) GetModifiedDate() string {
	if d != nil && d.ModifiedDate != nil {
		return *d.ModifiedDate
	}
	return ""
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (d *Document) GetName() string {
	if d != nil && d.Name != nil {
		return *d.Name
	}
	return ""
}

// GetResidenceID returns the ResidenceID field if it's non-nil, zero value otherwise.
func (d *Document) GetResidenceID() string {
	if d != nil && d.ResidenceID != nil {
		return *d.ResidenceID
	}
	return ""
}

// GetTemporaryURL returns the TemporaryURL field if it's non-nil, zero value otherwise.
func (d *Document) GetTemporaryURL() string {
	if d != nil && d.TemporaryURL != nil {
		return *d.TemporaryURL
	}
	return ""
}

// GetTemporaryURLThumb returns the TemporaryURLThumb field if it's non-nil, zero value otherwise.
func (d *Document) GetTemporaryURLThumb() string {
	if d != nil && d.TemporaryURLThumb != nil {
		return *d.TemporaryURLThumb
	}
	return ""
}

// GetTotalRows returns the TotalRows field if it's non-nil, zero value otherwise.
func (d *Document) GetTotalRows() int64 {
	if d != nil && d.TotalRows != nil {
		return *d.TotalRows
	}
	return 0
}

// GetUserFirstname returns the UserFirstname field if it's non-nil, zero value otherwise.
func (d *Document) GetUserFirstname() string {
	if d != nil && d.UserFirstname != nil {
		return *d.UserFirstname
	}
	return ""
}

// GetUserID returns the UserID field if it's non-nil, zero value otherwise.
func (d *Document) GetUserID() string {
	if d != nil && d.UserID != nil {
		return *d.UserID
	}
	return ""
}

// GetUserLastname returns the UserLastname field if it's non-nil, zero value otherwise.
func (d *Document) GetUserLastname() string {
	if d != nil && d.UserLastname != nil {
		return *d.UserLastname
	}
	return ""
}

// GetDocuments returns the Documents field.
func (d *DocumentResponse) GetDocuments() []*Document {
	if d != nil {
		return d.Documents
	}
	return nil
}

// GetErrors returns the Errors field.
func (e *ErrorResponse) GetErrors() []Error {
	if e != nil {
		return e.Errors
	}
	return nil
}

// GetResponse returns the Response field if it's non-nil, zero value otherwise.
func (e *ErrorResponse) GetResponse() http.Response {
	if e != nil && e.Response != nil {
		return *e.Response
	}
	return http.Response{}
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (e *Event) GetID() string {
	if e != nil && e.ID != nil {
		return *e.ID
	}
	return ""
}

// GetObject returns the Object field if it's non-nil, zero value otherwise.
func (e *Event) GetObject() string {
	if e != nil && e.Object != nil {
		return *e.Object
	}
	return ""
}

// GetObjectID returns the ObjectID field if it's non-nil, zero value otherwise.
func (e *Event) GetObjectID() string {
	if e != nil && e.ObjectID != nil {
		return *e.ObjectID
	}
	return ""
}

// GetPayloadSignature returns the PayloadSignature field if it's non-nil, zero value otherwise.
func (e *Event) GetPayloadSignature() string {
	if e != nil && e.PayloadSignature != nil {
		return *e.PayloadSignature
	}
	return ""
}

// GetRawPayload returns the RawPayload field if it's non-nil, zero value otherwise.
func (e *Event) GetRawPayload() json.RawMessage {
	if e != nil && e.RawPayload != nil {
		return *e.RawPayload
	}
	return json.RawMessage{}
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (e *Event) GetType() string {
	if e != nil && e.Type != nil {
		return *e.Type
	}
	return ""
}

// GetIdentificationID returns the IdentificationID field if it's non-nil, zero value otherwise.
func (i *Identification) GetIdentificationID() string {
	if i != nil && i.IdentificationID != nil {
		return *i.IdentificationID
	}
	return ""
}

// GetIdentificationURL returns the IdentificationURL field if it's non-nil, zero value otherwise.
func (i *Identification) GetIdentificationURL() string {
	if i != nil && i.IdentificationURL != nil {
		return *i.IdentificationURL
	}
	return ""
}

// GetIdentification returns the Identification field.
func (i *IdentificationResponse) GetIdentification() *Identification {
	if i != nil {
		return i.Identification
	}
	return nil
}

// GetComment returns the Comment field if it's non-nil, zero value otherwise.
func (k *KycLiveness) GetComment() string {
	if k != nil && k.Comment != nil {
		return *k.Comment
	}
	return ""
}

// GetIdentity returns the Identity field.
func (k *KycLiveness) GetIdentity() *KycLivenessIdentity {
	if k != nil {
		return k.Identity
	}
	return nil
}

// GetKycStatus returns the KycStatus field if it's non-nil, zero value otherwise.
func (k *KycLiveness) GetKycStatus() string {
	if k != nil && k.KycStatus != nil {
		return *k.KycStatus
	}
	return ""
}

// GetScore returns the Score field if it's non-nil, zero value otherwise.
func (k *KycLiveness) GetScore() int {
	if k != nil && k.Score != nil {
		return *k.Score
	}
	return 0
}

// GetStartedAt returns the StartedAt field if it's non-nil, zero value otherwise.
func (k *KycLiveness) GetStartedAt() time.Time {
	if k != nil && k.StartedAt != nil {
		return *k.StartedAt
	}
	return time.Time{}
}

// GetUpdatedAt returns the UpdatedAt field if it's non-nil, zero value otherwise.
func (k *KycLiveness) GetUpdatedAt() time.Time {
	if k != nil && k.UpdatedAt != nil {
		return *k.UpdatedAt
	}
	return time.Time{}
}

// GetUserID returns the UserID field if it's non-nil, zero value otherwise.
func (k *KycLiveness) GetUserID() string {
	if k != nil && k.UserID != nil {
		return *k.UserID
	}
	return ""
}

// GetBirthDate returns the BirthDate field if it's non-nil, zero value otherwise.
func (k *KycLivenessIdentity) GetBirthDate() string {
	if k != nil && k.BirthDate != nil {
		return *k.BirthDate
	}
	return ""
}

// GetFirstName returns the FirstName field if it's non-nil, zero value otherwise.
func (k *KycLivenessIdentity) GetFirstName() string {
	if k != nil && k.FirstName != nil {
		return *k.FirstName
	}
	return ""
}

// GetLastName returns the LastName field if it's non-nil, zero value otherwise.
func (k *KycLivenessIdentity) GetLastName() string {
	if k != nil && k.LastName != nil {
		return *k.LastName
	}
	return ""
}

// GetAdditionalData returns the AdditionalData field if it's non-nil, zero value otherwise.
func (p *Payin) GetAdditionalData() AdditionalDataOneOf {
	if p != nil && p.AdditionalData != nil {
		return *p.AdditionalData
	}
	return AdditionalDataOneOf{}
}

// GetAmount returns the Amount field if it's non-nil, zero value otherwise.
func (p *Payin) GetAmount() float64 {
	if p != nil && p.Amount != nil {
		return *p.Amount
	}
	return 0.0
}

// GetCodeStatus returns the CodeStatus field if it's non-nil, zero value otherwise.
func (p *Payin) GetCodeStatus() string {
	if p != nil && p.CodeStatus != nil {
		return *p.CodeStatus
	}
	return ""
}

// GetCreatedDate returns the CreatedDate field if it's non-nil, zero value otherwise.
func (p *Payin) GetCreatedDate() TimestampParis {
	if p != nil && p.CreatedDate != nil {
		return *p.CreatedDate
	}
	return TimestampParis{}
}

// GetCreatedIP returns the CreatedIP field if it's non-nil, zero value otherwise.
func (p *Payin) GetCreatedIP() string {
	if p != nil && p.CreatedIP != nil {
		return *p.CreatedIP
	}
	return ""
}

// GetCreditorAddressLine returns the CreditorAddressLine field if it's non-nil, zero value otherwise.
func (p *Payin) GetCreditorAddressLine() string {
	if p != nil && p.CreditorAddressLine != nil {
		return *p.CreditorAddressLine
	}
	return ""
}

// GetCreditorBIC returns the CreditorBIC field if it's non-nil, zero value otherwise.
func (p *Payin) GetCreditorBIC() string {
	if p != nil && p.CreditorBIC != nil {
		return *p.CreditorBIC
	}
	return ""
}

// GetCreditorCountry returns the CreditorCountry field if it's non-nil, zero value otherwise.
func (p *Payin) GetCreditorCountry() string {
	if p != nil && p.CreditorCountry != nil {
		return *p.CreditorCountry
	}
	return ""
}

// GetCreditorIBAN returns the CreditorIBAN field if it's non-nil, zero value otherwise.
func (p *Payin) GetCreditorIBAN() string {
	if p != nil && p.CreditorIBAN != nil {
		return *p.CreditorIBAN
	}
	return ""
}

// GetCreditorName returns the CreditorName field if it's non-nil, zero value otherwise.
func (p *Payin) GetCreditorName() string {
	if p != nil && p.CreditorName != nil {
		return *p.CreditorName
	}
	return ""
}

// GetDebitorIBAN returns the DebitorIBAN field if it's non-nil, zero value otherwise.
func (p *Payin) GetDebitorIBAN() string {
	if p != nil && p.DebitorIBAN != nil {
		return *p.DebitorIBAN
	}
	return ""
}

// GetDistributorFee returns the DistributorFee field if it's non-nil, zero value otherwise.
func (p *Payin) GetDistributorFee() float64 {
	if p != nil && p.DistributorFee != nil {
		return *p.DistributorFee
	}
	return 0.0
}

// GetForwardURL returns the ForwardURL field if it's non-nil, zero value otherwise.
func (p *Payin) GetForwardURL() string {
	if p != nil && p.ForwardURL != nil {
		return *p.ForwardURL
	}
	return ""
}

// GetIBANBIC returns the IBANBIC field if it's non-nil, zero value otherwise.
func (p *Payin) GetIBANBIC() string {
	if p != nil && p.IBANBIC != nil {
		return *p.IBANBIC
	}
	return ""
}

// GetIBANFullname returns the IBANFullname field if it's non-nil, zero value otherwise.
func (p *Payin) GetIBANFullname() string {
	if p != nil && p.IBANFullname != nil {
		return *p.IBANFullname
	}
	return ""
}

// GetIBANID returns the IBANID field if it's non-nil, zero value otherwise.
func (p *Payin) GetIBANID() string {
	if p != nil && p.IBANID != nil {
		return *p.IBANID
	}
	return ""
}

// GetIBANTxEndToEndID returns the IBANTxEndToEndID field if it's non-nil, zero value otherwise.
func (p *Payin) GetIBANTxEndToEndID() string {
	if p != nil && p.IBANTxEndToEndID != nil {
		return *p.IBANTxEndToEndID
	}
	return ""
}

// GetIBANTxID returns the IBANTxID field if it's non-nil, zero value otherwise.
func (p *Payin) GetIBANTxID() string {
	if p != nil && p.IBANTxID != nil {
		return *p.IBANTxID
	}
	return ""
}

// GetInformationStatus returns the InformationStatus field if it's non-nil, zero value otherwise.
func (p *Payin) GetInformationStatus() string {
	if p != nil && p.InformationStatus != nil {
		return *p.InformationStatus
	}
	return ""
}

// GetMandateID returns the MandateID field if it's non-nil, zero value otherwise.
func (p *Payin) GetMandateID() string {
	if p != nil && p.MandateID != nil {
		return *p.MandateID
	}
	return ""
}

// GetMessageToUser returns the MessageToUser field if it's non-nil, zero value otherwise.
func (p *Payin) GetMessageToUser() string {
	if p != nil && p.MessageToUser != nil {
		return *p.MessageToUser
	}
	return ""
}

// GetPayinDate returns the PayinDate field if it's non-nil, zero value otherwise.
func (p *Payin) GetPayinDate() Date {
	if p != nil && p.PayinDate != nil {
		return *p.PayinDate
	}
	return Date{}
}

// GetPayinID returns the PayinID field if it's non-nil, zero value otherwise.
func (p *Payin) GetPayinID() string {
	if p != nil && p.PayinID != nil {
		return *p.PayinID
	}
	return ""
}

// GetPayinStatus returns the PayinStatus field if it's non-nil, zero value otherwise.
func (p *Payin) GetPayinStatus() string {
	if p != nil && p.PayinStatus != nil {
		return *p.PayinStatus
	}
	return ""
}

// GetPayinTag returns the PayinTag field if it's non-nil, zero value otherwise.
func (p *Payin) GetPayinTag() string {
	if p != nil && p.PayinTag != nil {
		return *p.PayinTag
	}
	return ""
}

// GetPaymentAcceptedURL returns the PaymentAcceptedURL field if it's non-nil, zero value otherwise.
func (p *Payin) GetPaymentAcceptedURL() string {
	if p != nil && p.PaymentAcceptedURL != nil {
		return *p.PaymentAcceptedURL
	}
	return ""
}

// GetPaymentCanceledURL returns the PaymentCanceledURL field if it's non-nil, zero value otherwise.
func (p *Payin) GetPaymentCanceledURL() string {
	if p != nil && p.PaymentCanceledURL != nil {
		return *p.PaymentCanceledURL
	}
	return ""
}

// GetPaymentExceptionURL returns the PaymentExceptionURL field if it's non-nil, zero value otherwise.
func (p *Payin) GetPaymentExceptionURL() string {
	if p != nil && p.PaymentExceptionURL != nil {
		return *p.PaymentExceptionURL
	}
	return ""
}

// GetPaymentHTML returns the PaymentHTML field if it's non-nil, zero value otherwise.
func (p *Payin) GetPaymentHTML() string {
	if p != nil && p.PaymentHTML != nil {
		return *p.PaymentHTML
	}
	return ""
}

// GetPaymentLanguage returns the PaymentLanguage field if it's non-nil, zero value otherwise.
func (p *Payin) GetPaymentLanguage() string {
	if p != nil && p.PaymentLanguage != nil {
		return *p.PaymentLanguage
	}
	return ""
}

// GetPaymentMethodID returns the PaymentMethodID field if it's non-nil, zero value otherwise.
func (p *Payin) GetPaymentMethodID() string {
	if p != nil && p.PaymentMethodID != nil {
		return *p.PaymentMethodID
	}
	return ""
}

// GetPaymentPostDataURL returns the PaymentPostDataURL field if it's non-nil, zero value otherwise.
func (p *Payin) GetPaymentPostDataURL() string {
	if p != nil && p.PaymentPostDataURL != nil {
		return *p.PaymentPostDataURL
	}
	return ""
}

// GetPaymentPostURL returns the PaymentPostURL field if it's non-nil, zero value otherwise.
func (p *Payin) GetPaymentPostURL() string {
	if p != nil && p.PaymentPostURL != nil {
		return *p.PaymentPostURL
	}
	return ""
}

// GetPaymentRefusedURL returns the PaymentRefusedURL field if it's non-nil, zero value otherwise.
func (p *Payin) GetPaymentRefusedURL() string {
	if p != nil && p.PaymentRefusedURL != nil {
		return *p.PaymentRefusedURL
	}
	return ""
}

// GetPaymentWaitingURL returns the PaymentWaitingURL field if it's non-nil, zero value otherwise.
func (p *Payin) GetPaymentWaitingURL() string {
	if p != nil && p.PaymentWaitingURL != nil {
		return *p.PaymentWaitingURL
	}
	return ""
}

// GetRefundAmount returns the RefundAmount field if it's non-nil, zero value otherwise.
func (p *Payin) GetRefundAmount() float64 {
	if p != nil && p.RefundAmount != nil {
		return *p.RefundAmount
	}
	return 0.0
}

// GetSubtotalItems returns the SubtotalItems field if it's non-nil, zero value otherwise.
func (p *Payin) GetSubtotalItems() float64 {
	if p != nil && p.SubtotalItems != nil {
		return *p.SubtotalItems
	}
	return 0.0
}

// GetSubtotalServices returns the SubtotalServices field if it's non-nil, zero value otherwise.
func (p *Payin) GetSubtotalServices() float64 {
	if p != nil && p.SubtotalServices != nil {
		return *p.SubtotalServices
	}
	return 0.0
}

// GetSubtotalTax returns the SubtotalTax field if it's non-nil, zero value otherwise.
func (p *Payin) GetSubtotalTax() float64 {
	if p != nil && p.SubtotalTax != nil {
		return *p.SubtotalTax
	}
	return 0.0
}

// GetTotalRows returns the TotalRows field if it's non-nil, zero value otherwise.
func (p *Payin) GetTotalRows() int64 {
	if p != nil && p.TotalRows != nil {
		return *p.TotalRows
	}
	return 0
}

// GetUserFirstname returns the UserFirstname field if it's non-nil, zero value otherwise.
func (p *Payin) GetUserFirstname() string {
	if p != nil && p.UserFirstname != nil {
		return *p.UserFirstname
	}
	return ""
}

// GetUserID returns the UserID field if it's non-nil, zero value otherwise.
func (p *Payin) GetUserID() string {
	if p != nil && p.UserID != nil {
		return *p.UserID
	}
	return ""
}

// GetUserLastname returns the UserLastname field if it's non-nil, zero value otherwise.
func (p *Payin) GetUserLastname() string {
	if p != nil && p.UserLastname != nil {
		return *p.UserLastname
	}
	return ""
}

// GetVirtualIBANID returns the VirtualIBANID field if it's non-nil, zero value otherwise.
func (p *Payin) GetVirtualIBANID() string {
	if p != nil && p.VirtualIBANID != nil {
		return *p.VirtualIBANID
	}
	return ""
}

// GetVirtualIBANReference returns the VirtualIBANReference field if it's non-nil, zero value otherwise.
func (p *Payin) GetVirtualIBANReference() string {
	if p != nil && p.VirtualIBANReference != nil {
		return *p.VirtualIBANReference
	}
	return ""
}

// GetWalletAlias returns the WalletAlias field if it's non-nil, zero value otherwise.
func (p *Payin) GetWalletAlias() string {
	if p != nil && p.WalletAlias != nil {
		return *p.WalletAlias
	}
	return ""
}

// GetWalletEventName returns the WalletEventName field if it's non-nil, zero value otherwise.
func (p *Payin) GetWalletEventName() string {
	if p != nil && p.WalletEventName != nil {
		return *p.WalletEventName
	}
	return ""
}

// GetWalletID returns the WalletID field if it's non-nil, zero value otherwise.
func (p *Payin) GetWalletID() string {
	if p != nil && p.WalletID != nil {
		return *p.WalletID
	}
	return ""
}

// GetPayins returns the Payins field.
func (p *PayinResponse) GetPayins() []*Payin {
	if p != nil {
		return p.Payins
	}
	return nil
}

// GetAmount returns the Amount field if it's non-nil, zero value otherwise.
func (p *Payout) GetAmount() float64 {
	if p != nil && p.Amount != nil {
		return *p.Amount
	}
	return 0.0
}

// GetBeneficiaryID returns the BeneficiaryID field if it's non-nil, zero value otherwise.
func (p *Payout) GetBeneficiaryID() string {
	if p != nil && p.BeneficiaryID != nil {
		return *p.BeneficiaryID
	}
	return ""
}

// GetCreatedDate returns the CreatedDate field if it's non-nil, zero value otherwise.
func (p *Payout) GetCreatedDate() TimestampParis {
	if p != nil && p.CreatedDate != nil {
		return *p.CreatedDate
	}
	return TimestampParis{}
}

// GetLabel returns the Label field if it's non-nil, zero value otherwise.
func (p *Payout) GetLabel() string {
	if p != nil && p.Label != nil {
		return *p.Label
	}
	return ""
}

// GetModifiedDate returns the ModifiedDate field if it's non-nil, zero value otherwise.
func (p *Payout) GetModifiedDate() TimestampParis {
	if p != nil && p.ModifiedDate != nil {
		return *p.ModifiedDate
	}
	return TimestampParis{}
}

// GetPartnerFee returns the PartnerFee field if it's non-nil, zero value otherwise.
func (p *Payout) GetPartnerFee() float64 {
	if p != nil && p.PartnerFee != nil {
		return *p.PartnerFee
	}
	return 0.0
}

// GetPayoutDate returns the PayoutDate field if it's non-nil, zero value otherwise.
func (p *Payout) GetPayoutDate() Date {
	if p != nil && p.PayoutDate != nil {
		return *p.PayoutDate
	}
	return Date{}
}

// GetPayoutID returns the PayoutID field if it's non-nil, zero value otherwise.
func (p *Payout) GetPayoutID() string {
	if p != nil && p.PayoutID != nil {
		return *p.PayoutID
	}
	return ""
}

// GetPayoutStatus returns the PayoutStatus field if it's non-nil, zero value otherwise.
func (p *Payout) GetPayoutStatus() string {
	if p != nil && p.PayoutStatus != nil {
		return *p.PayoutStatus
	}
	return ""
}

// GetPayoutTag returns the PayoutTag field if it's non-nil, zero value otherwise.
func (p *Payout) GetPayoutTag() string {
	if p != nil && p.PayoutTag != nil {
		return *p.PayoutTag
	}
	return ""
}

// GetPayoutType returns the PayoutType field if it's non-nil, zero value otherwise.
func (p *Payout) GetPayoutType() string {
	if p != nil && p.PayoutType != nil {
		return *p.PayoutType
	}
	return ""
}

// GetPayoutTypeID returns the PayoutTypeID field if it's non-nil, zero value otherwise.
func (p *Payout) GetPayoutTypeID() string {
	if p != nil && p.PayoutTypeID != nil {
		return *p.PayoutTypeID
	}
	return ""
}

// GetTotalRows returns the TotalRows field if it's non-nil, zero value otherwise.
func (p *Payout) GetTotalRows() int64 {
	if p != nil && p.TotalRows != nil {
		return *p.TotalRows
	}
	return 0
}

// GetUniqueMandateReference returns the UniqueMandateReference field if it's non-nil, zero value otherwise.
func (p *Payout) GetUniqueMandateReference() string {
	if p != nil && p.UniqueMandateReference != nil {
		return *p.UniqueMandateReference
	}
	return ""
}

// GetUserFirstname returns the UserFirstname field if it's non-nil, zero value otherwise.
func (p *Payout) GetUserFirstname() string {
	if p != nil && p.UserFirstname != nil {
		return *p.UserFirstname
	}
	return ""
}

// GetUserID returns the UserID field if it's non-nil, zero value otherwise.
func (p *Payout) GetUserID() string {
	if p != nil && p.UserID != nil {
		return *p.UserID
	}
	return ""
}

// GetUserLastname returns the UserLastname field if it's non-nil, zero value otherwise.
func (p *Payout) GetUserLastname() string {
	if p != nil && p.UserLastname != nil {
		return *p.UserLastname
	}
	return ""
}

// GetWalletAlias returns the WalletAlias field if it's non-nil, zero value otherwise.
func (p *Payout) GetWalletAlias() string {
	if p != nil && p.WalletAlias != nil {
		return *p.WalletAlias
	}
	return ""
}

// GetWalletEventName returns the WalletEventName field if it's non-nil, zero value otherwise.
func (p *Payout) GetWalletEventName() string {
	if p != nil && p.WalletEventName != nil {
		return *p.WalletEventName
	}
	return ""
}

// GetWalletID returns the WalletID field if it's non-nil, zero value otherwise.
func (p *Payout) GetWalletID() string {
	if p != nil && p.WalletID != nil {
		return *p.WalletID
	}
	return ""
}

// GetPayouts returns the Payouts field.
func (p *PayoutResponse) GetPayouts() []*Payout {
	if p != nil {
		return p.Payouts
	}
	return nil
}

// GetBeneficiaryID returns the BeneficiaryID field if it's non-nil, zero value otherwise.
func (s *SDDB2BWhitelist) GetBeneficiaryID() string {
	if s != nil && s.BeneficiaryID != nil {
		return *s.BeneficiaryID
	}
	return ""
}

// GetIsRecurrent returns the IsRecurrent field if it's non-nil, zero value otherwise.
func (s *SDDB2BWhitelist) GetIsRecurrent() bool {
	if s != nil && s.IsRecurrent != nil {
		return *s.IsRecurrent
	}
	return false
}

// GetUniqueMandateReference returns the UniqueMandateReference field if it's non-nil, zero value otherwise.
func (s *SDDB2BWhitelist) GetUniqueMandateReference() string {
	if s != nil && s.UniqueMandateReference != nil {
		return *s.UniqueMandateReference
	}
	return ""
}

// GetBankaccountID returns the BankaccountID field if it's non-nil, zero value otherwise.
func (s *SepaSddr) GetBankaccountID() string {
	if s != nil && s.BankaccountID != nil {
		return *s.BankaccountID
	}
	return ""
}

// GetBeneficiaryID returns the BeneficiaryID field if it's non-nil, zero value otherwise.
func (s *SepaSddr) GetBeneficiaryID() string {
	if s != nil && s.BeneficiaryID != nil {
		return *s.BeneficiaryID
	}
	return ""
}

// GetCreditorAddress returns the CreditorAddress field if it's non-nil, zero value otherwise.
func (s *SepaSddr) GetCreditorAddress() string {
	if s != nil && s.CreditorAddress != nil {
		return *s.CreditorAddress
	}
	return ""
}

// GetCreditorCountry returns the CreditorCountry field if it's non-nil, zero value otherwise.
func (s *SepaSddr) GetCreditorCountry() string {
	if s != nil && s.CreditorCountry != nil {
		return *s.CreditorCountry
	}
	return ""
}

// GetCreditorName returns the CreditorName field if it's non-nil, zero value otherwise.
func (s *SepaSddr) GetCreditorName() string {
	if s != nil && s.CreditorName != nil {
		return *s.CreditorName
	}
	return ""
}

// GetDateOfSignature returns the DateOfSignature field if it's non-nil, zero value otherwise.
func (s *SepaSddr) GetDateOfSignature() string {
	if s != nil && s.DateOfSignature != nil {
		return *s.DateOfSignature
	}
	return ""
}

// GetDebitorAddress returns the DebitorAddress field if it's non-nil, zero value otherwise.
func (s *SepaSddr) GetDebitorAddress() string {
	if s != nil && s.DebitorAddress != nil {
		return *s.DebitorAddress
	}
	return ""
}

// GetDebitorCountry returns the DebitorCountry field if it's non-nil, zero value otherwise.
func (s *SepaSddr) GetDebitorCountry() string {
	if s != nil && s.DebitorCountry != nil {
		return *s.DebitorCountry
	}
	return ""
}

// GetDebitorName returns the DebitorName field if it's non-nil, zero value otherwise.
func (s *SepaSddr) GetDebitorName() string {
	if s != nil && s.DebitorName != nil {
		return *s.DebitorName
	}
	return ""
}

// GetInterbankSettlementAmount returns the InterbankSettlementAmount field if it's non-nil, zero value otherwise.
func (s *SepaSddr) GetInterbankSettlementAmount() string {
	if s != nil && s.InterbankSettlementAmount != nil {
		return *s.InterbankSettlementAmount
	}
	return ""
}

// GetMandateID returns the MandateID field if it's non-nil, zero value otherwise.
func (s *SepaSddr) GetMandateID() string {
	if s != nil && s.MandateID != nil {
		return *s.MandateID
	}
	return ""
}

// GetRejectReasonCode returns the RejectReasonCode field if it's non-nil, zero value otherwise.
func (s *SepaSddr) GetRejectReasonCode() string {
	if s != nil && s.RejectReasonCode != nil {
		return *s.RejectReasonCode
	}
	return ""
}

// GetRequestedCollectionDate returns the RequestedCollectionDate field if it's non-nil, zero value otherwise.
func (s *SepaSddr) GetRequestedCollectionDate() string {
	if s != nil && s.RequestedCollectionDate != nil {
		return *s.RequestedCollectionDate
	}
	return ""
}

// GetSepaCreditorIdentifier returns the SepaCreditorIdentifier field if it's non-nil, zero value otherwise.
func (s *SepaSddr) GetSepaCreditorIdentifier() string {
	if s != nil && s.SepaCreditorIdentifier != nil {
		return *s.SepaCreditorIdentifier
	}
	return ""
}

// GetSequenceType returns the SequenceType field if it's non-nil, zero value otherwise.
func (s *SepaSddr) GetSequenceType() string {
	if s != nil && s.SequenceType != nil {
		return *s.SequenceType
	}
	return ""
}

// GetTransactionID returns the TransactionID field if it's non-nil, zero value otherwise.
func (s *SepaSddr) GetTransactionID() string {
	if s != nil && s.TransactionID != nil {
		return *s.TransactionID
	}
	return ""
}

// GetUnstructuredField returns the UnstructuredField field if it's non-nil, zero value otherwise.
func (s *SepaSddr) GetUnstructuredField() string {
	if s != nil && s.UnstructuredField != nil {
		return *s.UnstructuredField
	}
	return ""
}

// GetVirtualIbanID returns the VirtualIbanID field if it's non-nil, zero value otherwise.
func (s *SepaSddr) GetVirtualIbanID() string {
	if s != nil && s.VirtualIbanID != nil {
		return *s.VirtualIbanID
	}
	return ""
}

// GetWalletID returns the WalletID field if it's non-nil, zero value otherwise.
func (s *SepaSddr) GetWalletID() int64 {
	if s != nil && s.WalletID != nil {
		return *s.WalletID
	}
	return 0
}

// GetSepaSddrs returns the SepaSddrs field.
func (s *SepaSddrResponse) GetSepaSddrs() []*SepaSddr {
	if s != nil {
		return s.SepaSddrs
	}
	return nil
}

// GetCountry returns the Country field if it's non-nil, zero value otherwise.
func (t *TaxResidence) GetCountry() string {
	if t != nil && t.Country != nil {
		return *t.Country
	}
	return ""
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (t *TaxResidence) GetID() int64 {
	if t != nil && t.ID != nil {
		return *t.ID
	}
	return 0
}

// GetLiabilityWaiver returns the LiabilityWaiver field if it's non-nil, zero value otherwise.
func (t *TaxResidence) GetLiabilityWaiver() bool {
	if t != nil && t.LiabilityWaiver != nil {
		return *t.LiabilityWaiver
	}
	return false
}

// GetTaxPayerID returns the TaxPayerID field if it's non-nil, zero value otherwise.
func (t *TaxResidence) GetTaxPayerID() string {
	if t != nil && t.TaxPayerID != nil {
		return *t.TaxPayerID
	}
	return ""
}

// GetUserID returns the UserID field if it's non-nil, zero value otherwise.
func (t *TaxResidence) GetUserID() int64 {
	if t != nil && t.UserID != nil {
		return *t.UserID
	}
	return 0
}

// GetTaxResidences returns the TaxResidences field.
func (t *TaxResidencesResponse) GetTaxResidences() []*TaxResidence {
	if t != nil {
		return t.TaxResidences
	}
	return nil
}

// GetAmount returns the Amount field if it's non-nil, zero value otherwise.
func (t *Transfer) GetAmount() float64 {
	if t != nil && t.Amount != nil {
		return *t.Amount
	}
	return 0.0
}

// GetBeneficiaryWalletAlias returns the BeneficiaryWalletAlias field if it's non-nil, zero value otherwise.
func (t *Transfer) GetBeneficiaryWalletAlias() string {
	if t != nil && t.BeneficiaryWalletAlias != nil {
		return *t.BeneficiaryWalletAlias
	}
	return ""
}

// GetBeneficiaryWalletEventName returns the BeneficiaryWalletEventName field if it's non-nil, zero value otherwise.
func (t *Transfer) GetBeneficiaryWalletEventName() string {
	if t != nil && t.BeneficiaryWalletEventName != nil {
		return *t.BeneficiaryWalletEventName
	}
	return ""
}

// GetBeneficiaryWalletID returns the BeneficiaryWalletID field if it's non-nil, zero value otherwise.
func (t *Transfer) GetBeneficiaryWalletID() string {
	if t != nil && t.BeneficiaryWalletID != nil {
		return *t.BeneficiaryWalletID
	}
	return ""
}

// GetBeneficiaryWalletTypeID returns the BeneficiaryWalletTypeID field if it's non-nil, zero value otherwise.
func (t *Transfer) GetBeneficiaryWalletTypeID() string {
	if t != nil && t.BeneficiaryWalletTypeID != nil {
		return *t.BeneficiaryWalletTypeID
	}
	return ""
}

// GetCreatedDate returns the CreatedDate field if it's non-nil, zero value otherwise.
func (t *Transfer) GetCreatedDate() TimestampParis {
	if t != nil && t.CreatedDate != nil {
		return *t.CreatedDate
	}
	return TimestampParis{}
}

// GetLabel returns the Label field if it's non-nil, zero value otherwise.
func (t *Transfer) GetLabel() string {
	if t != nil && t.Label != nil {
		return *t.Label
	}
	return ""
}

// GetModifiedDate returns the ModifiedDate field if it's non-nil, zero value otherwise.
func (t *Transfer) GetModifiedDate() TimestampParis {
	if t != nil && t.ModifiedDate != nil {
		return *t.ModifiedDate
	}
	return TimestampParis{}
}

// GetTotalRows returns the TotalRows field if it's non-nil, zero value otherwise.
func (t *Transfer) GetTotalRows() int64 {
	if t != nil && t.TotalRows != nil {
		return *t.TotalRows
	}
	return 0
}

// GetTransferDate returns the TransferDate field if it's non-nil, zero value otherwise.
func (t *Transfer) GetTransferDate() Date {
	if t != nil && t.TransferDate != nil {
		return *t.TransferDate
	}
	return Date{}
}

// GetTransferID returns the TransferID field if it's non-nil, zero value otherwise.
func (t *Transfer) GetTransferID() string {
	if t != nil && t.TransferID != nil {
		return *t.TransferID
	}
	return ""
}

// GetTransferStatus returns the TransferStatus field if it's non-nil, zero value otherwise.
func (t *Transfer) GetTransferStatus() string {
	if t != nil && t.TransferStatus != nil {
		return *t.TransferStatus
	}
	return ""
}

// GetTransferTag returns the TransferTag field if it's non-nil, zero value otherwise.
func (t *Transfer) GetTransferTag() string {
	if t != nil && t.TransferTag != nil {
		return *t.TransferTag
	}
	return ""
}

// GetWalletAlias returns the WalletAlias field if it's non-nil, zero value otherwise.
func (t *Transfer) GetWalletAlias() string {
	if t != nil && t.WalletAlias != nil {
		return *t.WalletAlias
	}
	return ""
}

// GetWalletEventName returns the WalletEventName field if it's non-nil, zero value otherwise.
func (t *Transfer) GetWalletEventName() string {
	if t != nil && t.WalletEventName != nil {
		return *t.WalletEventName
	}
	return ""
}

// GetWalletID returns the WalletID field if it's non-nil, zero value otherwise.
func (t *Transfer) GetWalletID() string {
	if t != nil && t.WalletID != nil {
		return *t.WalletID
	}
	return ""
}

// GetWalletTypeID returns the WalletTypeID field if it's non-nil, zero value otherwise.
func (t *Transfer) GetWalletTypeID() string {
	if t != nil && t.WalletTypeID != nil {
		return *t.WalletTypeID
	}
	return ""
}

// GetTransfers returns the Transfers field.
func (t *TransferResponse) GetTransfers() []*Transfer {
	if t != nil {
		return t.Transfers
	}
	return nil
}

// GetActivityOutsideEu returns the ActivityOutsideEu field if it's non-nil, zero value otherwise.
func (u *User) GetActivityOutsideEu() string {
	if u != nil && u.ActivityOutsideEu != nil {
		return *u.ActivityOutsideEu
	}
	return ""
}

// GetAddress1 returns the Address1 field if it's non-nil, zero value otherwise.
func (u *User) GetAddress1() string {
	if u != nil && u.Address1 != nil {
		return *u.Address1
	}
	return ""
}

// GetAddress2 returns the Address2 field if it's non-nil, zero value otherwise.
func (u *User) GetAddress2() string {
	if u != nil && u.Address2 != nil {
		return *u.Address2
	}
	return ""
}

// GetAddress3 returns the Address3 field if it's non-nil, zero value otherwise.
func (u *User) GetAddress3() string {
	if u != nil && u.Address3 != nil {
		return *u.Address3
	}
	return ""
}

// GetBirthCountry returns the BirthCountry field if it's non-nil, zero value otherwise.
func (u *User) GetBirthCountry() string {
	if u != nil && u.BirthCountry != nil {
		return *u.BirthCountry
	}
	return ""
}

// GetBirthday returns the Birthday field if it's non-nil, zero value otherwise.
func (u *User) GetBirthday() Date {
	if u != nil && u.Birthday != nil {
		return *u.Birthday
	}
	return Date{}
}

// GetCity returns the City field if it's non-nil, zero value otherwise.
func (u *User) GetCity() string {
	if u != nil && u.City != nil {
		return *u.City
	}
	return ""
}

// GetClientID returns the ClientID field if it's non-nil, zero value otherwise.
func (u *User) GetClientID() string {
	if u != nil && u.ClientID != nil {
		return *u.ClientID
	}
	return ""
}

// GetCodeStatus returns the CodeStatus field if it's non-nil, zero value otherwise.
func (u *User) GetCodeStatus() string {
	if u != nil && u.CodeStatus != nil {
		return *u.CodeStatus
	}
	return ""
}

// GetControllingPersonType returns the ControllingPersonType field if it's non-nil, zero value otherwise.
func (u *User) GetControllingPersonType() string {
	if u != nil && u.ControllingPersonType != nil {
		return *u.ControllingPersonType
	}
	return ""
}

// GetCountry returns the Country field if it's non-nil, zero value otherwise.
func (u *User) GetCountry() string {
	if u != nil && u.Country != nil {
		return *u.Country
	}
	return ""
}

// GetCountryName returns the CountryName field if it's non-nil, zero value otherwise.
func (u *User) GetCountryName() string {
	if u != nil && u.CountryName != nil {
		return *u.CountryName
	}
	return ""
}

// GetCreatedDate returns the CreatedDate field if it's non-nil, zero value otherwise.
func (u *User) GetCreatedDate() TimestampParis {
	if u != nil && u.CreatedDate != nil {
		return *u.CreatedDate
	}
	return TimestampParis{}
}

// GetEconomicSanctions returns the EconomicSanctions field if it's non-nil, zero value otherwise.
func (u *User) GetEconomicSanctions() string {
	if u != nil && u.EconomicSanctions != nil {
		return *u.EconomicSanctions
	}
	return ""
}

// GetEffectiveBeneficiary returns the EffectiveBeneficiary field if it's non-nil, zero value otherwise.
func (u *User) GetEffectiveBeneficiary() string {
	if u != nil && u.EffectiveBeneficiary != nil {
		return *u.EffectiveBeneficiary
	}
	return ""
}

// GetEmail returns the Email field if it's non-nil, zero value otherwise.
func (u *User) GetEmail() string {
	if u != nil && u.Email != nil {
		return *u.Email
	}
	return ""
}

// GetEmployeeType returns the EmployeeType field if it's non-nil, zero value otherwise.
func (u *User) GetEmployeeType() string {
	if u != nil && u.EmployeeType != nil {
		return *u.EmployeeType
	}
	return ""
}

// GetEntityType returns the EntityType field if it's non-nil, zero value otherwise.
func (u *User) GetEntityType() string {
	if u != nil && u.EntityType != nil {
		return *u.EntityType
	}
	return ""
}

// GetFirstname returns the Firstname field if it's non-nil, zero value otherwise.
func (u *User) GetFirstname() string {
	if u != nil && u.Firstname != nil {
		return *u.Firstname
	}
	return ""
}

// GetIncomeRange returns the IncomeRange field if it's non-nil, zero value otherwise.
func (u *User) GetIncomeRange() string {
	if u != nil && u.IncomeRange != nil {
		return *u.IncomeRange
	}
	return ""
}

// GetInformationStatus returns the InformationStatus field if it's non-nil, zero value otherwise.
func (u *User) GetInformationStatus() string {
	if u != nil && u.InformationStatus != nil {
		return *u.InformationStatus
	}
	return ""
}

// GetInvolvedSanctions returns the InvolvedSanctions field if it's non-nil, zero value otherwise.
func (u *User) GetInvolvedSanctions() string {
	if u != nil && u.InvolvedSanctions != nil {
		return *u.InvolvedSanctions
	}
	return ""
}

// GetIsFreezed returns the IsFreezed field if it's non-nil, zero value otherwise.
func (u *User) GetIsFreezed() int64 {
	if u != nil && u.IsFreezed != nil {
		return *u.IsFreezed
	}
	return 0
}

// GetKycLevel returns the KycLevel field if it's non-nil, zero value otherwise.
func (u *User) GetKycLevel() Level {
	if u != nil && u.KycLevel != nil {
		return *u.KycLevel
	}
	return LevelNone
}

// GetKycReview returns the KycReview field if it's non-nil, zero value otherwise.
func (u *User) GetKycReview() Review {
	if u != nil && u.KycReview != nil {
		return *u.KycReview
	}
	return ReviewNone
}

// GetKycReviewComment returns the KycReviewComment field if it's non-nil, zero value otherwise.
func (u *User) GetKycReviewComment() string {
	if u != nil && u.KycReviewComment != nil {
		return *u.KycReviewComment
	}
	return ""
}

// GetLanguage returns the Language field if it's non-nil, zero value otherwise.
func (u *User) GetLanguage() string {
	if u != nil && u.Language != nil {
		return *u.Language
	}
	return ""
}

// GetLastname returns the Lastname field if it's non-nil, zero value otherwise.
func (u *User) GetLastname() string {
	if u != nil && u.Lastname != nil {
		return *u.Lastname
	}
	return ""
}

// GetLegalAnnualTurnOver returns the LegalAnnualTurnOver field if it's non-nil, zero value otherwise.
func (u *User) GetLegalAnnualTurnOver() string {
	if u != nil && u.LegalAnnualTurnOver != nil {
		return *u.LegalAnnualTurnOver
	}
	return ""
}

// GetLegalForm returns the LegalForm field if it's non-nil, zero value otherwise.
func (u *User) GetLegalForm() string {
	if u != nil && u.LegalForm != nil {
		return *u.LegalForm
	}
	return ""
}

// GetLegalName returns the LegalName field if it's non-nil, zero value otherwise.
func (u *User) GetLegalName() string {
	if u != nil && u.LegalName != nil {
		return *u.LegalName
	}
	return ""
}

// GetLegalNameEmbossed returns the LegalNameEmbossed field if it's non-nil, zero value otherwise.
func (u *User) GetLegalNameEmbossed() string {
	if u != nil && u.LegalNameEmbossed != nil {
		return *u.LegalNameEmbossed
	}
	return ""
}

// GetLegalNetIncomeRange returns the LegalNetIncomeRange field if it's non-nil, zero value otherwise.
func (u *User) GetLegalNetIncomeRange() string {
	if u != nil && u.LegalNetIncomeRange != nil {
		return *u.LegalNetIncomeRange
	}
	return ""
}

// GetLegalNumberOfEmployeeRange returns the LegalNumberOfEmployeeRange field if it's non-nil, zero value otherwise.
func (u *User) GetLegalNumberOfEmployeeRange() string {
	if u != nil && u.LegalNumberOfEmployeeRange != nil {
		return *u.LegalNumberOfEmployeeRange
	}
	return ""
}

// GetLegalRegistrationDate returns the LegalRegistrationDate field if it's non-nil, zero value otherwise.
func (u *User) GetLegalRegistrationDate() Date {
	if u != nil && u.LegalRegistrationDate != nil {
		return *u.LegalRegistrationDate
	}
	return Date{}
}

// GetLegalRegistrationNumber returns the LegalRegistrationNumber field if it's non-nil, zero value otherwise.
func (u *User) GetLegalRegistrationNumber() string {
	if u != nil && u.LegalRegistrationNumber != nil {
		return *u.LegalRegistrationNumber
	}
	return ""
}

// GetLegalSector returns the LegalSector field if it's non-nil, zero value otherwise.
func (u *User) GetLegalSector() string {
	if u != nil && u.LegalSector != nil {
		return *u.LegalSector
	}
	return ""
}

// GetLegalShareCapital returns the LegalShareCapital field if it's non-nil, zero value otherwise.
func (u *User) GetLegalShareCapital() string {
	if u != nil && u.LegalShareCapital != nil {
		return *u.LegalShareCapital
	}
	return ""
}

// GetLegalTvaNumber returns the LegalTvaNumber field if it's non-nil, zero value otherwise.
func (u *User) GetLegalTvaNumber() string {
	if u != nil && u.LegalTvaNumber != nil {
		return *u.LegalTvaNumber
	}
	return ""
}

// GetMiddleNames returns the MiddleNames field if it's non-nil, zero value otherwise.
func (u *User) GetMiddleNames() string {
	if u != nil && u.MiddleNames != nil {
		return *u.MiddleNames
	}
	return ""
}

// GetMobile returns the Mobile field if it's non-nil, zero value otherwise.
func (u *User) GetMobile() string {
	if u != nil && u.Mobile != nil {
		return *u.Mobile
	}
	return ""
}

// GetModifiedDate returns the ModifiedDate field if it's non-nil, zero value otherwise.
func (u *User) GetModifiedDate() TimestampParis {
	if u != nil && u.ModifiedDate != nil {
		return *u.ModifiedDate
	}
	return TimestampParis{}
}

// GetNationality returns the Nationality field if it's non-nil, zero value otherwise.
func (u *User) GetNationality() string {
	if u != nil && u.Nationality != nil {
		return *u.Nationality
	}
	return ""
}

// GetNationalityOther returns the NationalityOther field if it's non-nil, zero value otherwise.
func (u *User) GetNationalityOther() string {
	if u != nil && u.NationalityOther != nil {
		return *u.NationalityOther
	}
	return ""
}

// GetOccupation returns the Occupation field if it's non-nil, zero value otherwise.
func (u *User) GetOccupation() string {
	if u != nil && u.Occupation != nil {
		return *u.Occupation
	}
	return ""
}

// GetParentType returns the ParentType field if it's non-nil, zero value otherwise.
func (u *User) GetParentType() string {
	if u != nil && u.ParentType != nil {
		return *u.ParentType
	}
	return ""
}

// GetParentUserID returns the ParentUserID field if it's non-nil, zero value otherwise.
func (u *User) GetParentUserID() string {
	if u != nil && u.ParentUserID != nil {
		return *u.ParentUserID
	}
	return ""
}

// GetPayinCount returns the PayinCount field if it's non-nil, zero value otherwise.
func (u *User) GetPayinCount() int64 {
	if u != nil && u.PayinCount != nil {
		return *u.PayinCount
	}
	return 0
}

// GetPersonalAssets returns the PersonalAssets field if it's non-nil, zero value otherwise.
func (u *User) GetPersonalAssets() string {
	if u != nil && u.PersonalAssets != nil {
		return *u.PersonalAssets
	}
	return ""
}

// GetPhone returns the Phone field if it's non-nil, zero value otherwise.
func (u *User) GetPhone() string {
	if u != nil && u.Phone != nil {
		return *u.Phone
	}
	return ""
}

// GetPlaceOfBirth returns the PlaceOfBirth field if it's non-nil, zero value otherwise.
func (u *User) GetPlaceOfBirth() string {
	if u != nil && u.PlaceOfBirth != nil {
		return *u.PlaceOfBirth
	}
	return ""
}

// GetPosition returns the Position field if it's non-nil, zero value otherwise.
func (u *User) GetPosition() string {
	if u != nil && u.Position != nil {
		return *u.Position
	}
	return ""
}

// GetPostcode returns the Postcode field if it's non-nil, zero value otherwise.
func (u *User) GetPostcode() string {
	if u != nil && u.Postcode != nil {
		return *u.Postcode
	}
	return ""
}

// GetResidentCountriesSanctions returns the ResidentCountriesSanctions field if it's non-nil, zero value otherwise.
func (u *User) GetResidentCountriesSanctions() string {
	if u != nil && u.ResidentCountriesSanctions != nil {
		return *u.ResidentCountriesSanctions
	}
	return ""
}

// GetSanctionsQuestionnaireDate returns the SanctionsQuestionnaireDate field if it's non-nil, zero value otherwise.
func (u *User) GetSanctionsQuestionnaireDate() string {
	if u != nil && u.SanctionsQuestionnaireDate != nil {
		return *u.SanctionsQuestionnaireDate
	}
	return ""
}

// GetSepaCreditorIdentifier returns the SepaCreditorIdentifier field if it's non-nil, zero value otherwise.
func (u *User) GetSepaCreditorIdentifier() string {
	if u != nil && u.SepaCreditorIdentifier != nil {
		return *u.SepaCreditorIdentifier
	}
	return ""
}

// GetSpecifiedUSPerson returns the SpecifiedUSPerson field if it's non-nil, zero value otherwise.
func (u *User) GetSpecifiedUSPerson() string {
	if u != nil && u.SpecifiedUSPerson != nil {
		return *u.SpecifiedUSPerson
	}
	return ""
}

// GetState returns the State field if it's non-nil, zero value otherwise.
func (u *User) GetState() string {
	if u != nil && u.State != nil {
		return *u.State
	}
	return ""
}

// GetTaxNumber returns the TaxNumber field if it's non-nil, zero value otherwise.
func (u *User) GetTaxNumber() string {
	if u != nil && u.TaxNumber != nil {
		return *u.TaxNumber
	}
	return ""
}

// GetTaxResidence returns the TaxResidence field if it's non-nil, zero value otherwise.
func (u *User) GetTaxResidence() string {
	if u != nil && u.TaxResidence != nil {
		return *u.TaxResidence
	}
	return ""
}

// GetTitle returns the Title field if it's non-nil, zero value otherwise.
func (u *User) GetTitle() string {
	if u != nil && u.Title != nil {
		return *u.Title
	}
	return ""
}

// GetTotalRows returns the TotalRows field if it's non-nil, zero value otherwise.
func (u *User) GetTotalRows() int64 {
	if u != nil && u.TotalRows != nil {
		return *u.TotalRows
	}
	return 0
}

// GetUserID returns the UserID field if it's non-nil, zero value otherwise.
func (u *User) GetUserID() string {
	if u != nil && u.UserID != nil {
		return *u.UserID
	}
	return ""
}

// GetUserStatus returns the UserStatus field if it's non-nil, zero value otherwise.
func (u *User) GetUserStatus() string {
	if u != nil && u.UserStatus != nil {
		return *u.UserStatus
	}
	return ""
}

// GetUserTag returns the UserTag field if it's non-nil, zero value otherwise.
func (u *User) GetUserTag() string {
	if u != nil && u.UserTag != nil {
		return *u.UserTag
	}
	return ""
}

// GetUserTypeID returns the UserTypeID field if it's non-nil, zero value otherwise.
func (u *User) GetUserTypeID() string {
	if u != nil && u.UserTypeID != nil {
		return *u.UserTypeID
	}
	return ""
}

// GetWalletCount returns the WalletCount field if it's non-nil, zero value otherwise.
func (u *User) GetWalletCount() int64 {
	if u != nil && u.WalletCount != nil {
		return *u.WalletCount
	}
	return 0
}

// GetUsers returns the Users field.
func (u *UserResponse) GetUsers() []*User {
	if u != nil {
		return u.Users
	}
	return nil
}

// GetAlias returns the Alias field if it's non-nil, zero value otherwise.
func (w *Wallet) GetAlias() string {
	if w != nil && w.Alias != nil {
		return *w.Alias
	}
	return ""
}

// GetAuthorizedBalance returns the AuthorizedBalance field if it's non-nil, zero value otherwise.
func (w *Wallet) GetAuthorizedBalance() float64 {
	if w != nil && w.AuthorizedBalance != nil {
		return *w.AuthorizedBalance
	}
	return 0.0
}

// GetBIC returns the BIC field if it's non-nil, zero value otherwise.
func (w *Wallet) GetBIC() string {
	if w != nil && w.BIC != nil {
		return *w.BIC
	}
	return ""
}

// GetCodeStatus returns the CodeStatus field if it's non-nil, zero value otherwise.
func (w *Wallet) GetCodeStatus() string {
	if w != nil && w.CodeStatus != nil {
		return *w.CodeStatus
	}
	return ""
}

// GetContractSigned returns the ContractSigned field if it's non-nil, zero value otherwise.
func (w *Wallet) GetContractSigned() string {
	if w != nil && w.ContractSigned != nil {
		return *w.ContractSigned
	}
	return ""
}

// GetCreatedDate returns the CreatedDate field if it's non-nil, zero value otherwise.
func (w *Wallet) GetCreatedDate() TimestampParis {
	if w != nil && w.CreatedDate != nil {
		return *w.CreatedDate
	}
	return TimestampParis{}
}

// GetDate returns the Date field if it's non-nil, zero value otherwise.
func (w *Wallet) GetDate() Date {
	if w != nil && w.Date != nil {
		return *w.Date
	}
	return Date{}
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (w *Wallet) GetDescription() string {
	if w != nil && w.Description != nil {
		return *w.Description
	}
	return ""
}

// GetIBAN returns the IBAN field if it's non-nil, zero value otherwise.
func (w *Wallet) GetIBAN() string {
	if w != nil && w.IBAN != nil {
		return *w.IBAN
	}
	return ""
}

// GetInformationStatus returns the InformationStatus field if it's non-nil, zero value otherwise.
func (w *Wallet) GetInformationStatus() string {
	if w != nil && w.InformationStatus != nil {
		return *w.InformationStatus
	}
	return ""
}

// GetJointUserID returns the JointUserID field if it's non-nil, zero value otherwise.
func (w *Wallet) GetJointUserID() string {
	if w != nil && w.JointUserID != nil {
		return *w.JointUserID
	}
	return ""
}

// GetModifiedDate returns the ModifiedDate field if it's non-nil, zero value otherwise.
func (w *Wallet) GetModifiedDate() TimestampParis {
	if w != nil && w.ModifiedDate != nil {
		return *w.ModifiedDate
	}
	return TimestampParis{}
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (w *Wallet) GetName() string {
	if w != nil && w.Name != nil {
		return *w.Name
	}
	return ""
}

// GetPayinCount returns the PayinCount field if it's non-nil, zero value otherwise.
func (w *Wallet) GetPayinCount() int64 {
	if w != nil && w.PayinCount != nil {
		return *w.PayinCount
	}
	return 0
}

// GetPayinEndDate returns the PayinEndDate field if it's non-nil, zero value otherwise.
func (w *Wallet) GetPayinEndDate() Date {
	if w != nil && w.PayinEndDate != nil {
		return *w.PayinEndDate
	}
	return Date{}
}

// GetPayinStartDate returns the PayinStartDate field if it's non-nil, zero value otherwise.
func (w *Wallet) GetPayinStartDate() Date {
	if w != nil && w.PayinStartDate != nil {
		return *w.PayinStartDate
	}
	return Date{}
}

// GetPayoutCount returns the PayoutCount field if it's non-nil, zero value otherwise.
func (w *Wallet) GetPayoutCount() int64 {
	if w != nil && w.PayoutCount != nil {
		return *w.PayoutCount
	}
	return 0
}

// GetSolde returns the Solde field if it's non-nil, zero value otherwise.
func (w *Wallet) GetSolde() float64 {
	if w != nil && w.Solde != nil {
		return *w.Solde
	}
	return 0.0
}

// GetTariffID returns the TariffID field if it's non-nil, zero value otherwise.
func (w *Wallet) GetTariffID() string {
	if w != nil && w.TariffID != nil {
		return *w.TariffID
	}
	return ""
}

// GetTotalRows returns the TotalRows field if it's non-nil, zero value otherwise.
func (w *Wallet) GetTotalRows() int64 {
	if w != nil && w.TotalRows != nil {
		return *w.TotalRows
	}
	return 0
}

// GetTransferCount returns the TransferCount field if it's non-nil, zero value otherwise.
func (w *Wallet) GetTransferCount() int64 {
	if w != nil && w.TransferCount != nil {
		return *w.TransferCount
	}
	return 0
}

// GetURLImage returns the URLImage field if it's non-nil, zero value otherwise.
func (w *Wallet) GetURLImage() string {
	if w != nil && w.URLImage != nil {
		return *w.URLImage
	}
	return ""
}

// GetUserFirstname returns the UserFirstname field if it's non-nil, zero value otherwise.
func (w *Wallet) GetUserFirstname() string {
	if w != nil && w.UserFirstname != nil {
		return *w.UserFirstname
	}
	return ""
}

// GetUserID returns the UserID field if it's non-nil, zero value otherwise.
func (w *Wallet) GetUserID() string {
	if w != nil && w.UserID != nil {
		return *w.UserID
	}
	return ""
}

// GetUserLastname returns the UserLastname field if it's non-nil, zero value otherwise.
func (w *Wallet) GetUserLastname() string {
	if w != nil && w.UserLastname != nil {
		return *w.UserLastname
	}
	return ""
}

// GetWalletID returns the WalletID field if it's non-nil, zero value otherwise.
func (w *Wallet) GetWalletID() string {
	if w != nil && w.WalletID != nil {
		return *w.WalletID
	}
	return ""
}

// GetWalletStatus returns the WalletStatus field if it's non-nil, zero value otherwise.
func (w *Wallet) GetWalletStatus() string {
	if w != nil && w.WalletStatus != nil {
		return *w.WalletStatus
	}
	return ""
}

// GetWalletTag returns the WalletTag field if it's non-nil, zero value otherwise.
func (w *Wallet) GetWalletTag() string {
	if w != nil && w.WalletTag != nil {
		return *w.WalletTag
	}
	return ""
}

// GetWalletTypeID returns the WalletTypeID field if it's non-nil, zero value otherwise.
func (w *Wallet) GetWalletTypeID() string {
	if w != nil && w.WalletTypeID != nil {
		return *w.WalletTypeID
	}
	return ""
}

// GetWallets returns the Wallets field.
func (w *WalletResponse) GetWallets() []*Wallet {
	if w != nil {
		return w.Wallets
	}
	return nil
}
