// Code generated by gen_accessors; DO NOT EDIT.

package treezor

import (
	"encoding/json"
	"net/http"
)

// GetIdempotencyKey returns the IdempotencyKey field if it's non-nil, zero value otherwise.
func (a *Access) GetIdempotencyKey() string {
	if a != nil && a.IdempotencyKey != nil {
		return *a.IdempotencyKey
	}
	return ""
}

// GetUserID returns the UserID field if it's non-nil, zero value otherwise.
func (a *Access) GetUserID() string {
	if a != nil && a.UserID != nil {
		return *a.UserID
	}
	return ""
}

// GetUserIP returns the UserIP field if it's non-nil, zero value otherwise.
func (a *Access) GetUserIP() string {
	if a != nil && a.UserIP != nil {
		return *a.UserIP
	}
	return ""
}

// GetBalances returns the Balances field.
func (b *BalanceResponse) GetBalances() []*Balance {
	if b != nil {
		return b.Balances
	}
	return nil
}

// GetAddress returns the Address field if it's non-nil, zero value otherwise.
func (b *Beneficiary) GetAddress() string {
	if b != nil && b.Address != nil {
		return *b.Address
	}
	return ""
}

// GetBIC returns the BIC field if it's non-nil, zero value otherwise.
func (b *Beneficiary) GetBIC() string {
	if b != nil && b.BIC != nil {
		return *b.BIC
	}
	return ""
}

// GetIBAN returns the IBAN field if it's non-nil, zero value otherwise.
func (b *Beneficiary) GetIBAN() string {
	if b != nil && b.IBAN != nil {
		return *b.IBAN
	}
	return ""
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (b *Beneficiary) GetName() string {
	if b != nil && b.Name != nil {
		return *b.Name
	}
	return ""
}

// GetNickName returns the NickName field if it's non-nil, zero value otherwise.
func (b *Beneficiary) GetNickName() string {
	if b != nil && b.NickName != nil {
		return *b.NickName
	}
	return ""
}

// GetSDDB2BWhitelist returns the SDDB2BWhitelist field.
func (b *Beneficiary) GetSDDB2BWhitelist() []*SDDB2BWhitelist {
	if b != nil {
		return b.SDDB2BWhitelist
	}
	return nil
}

// GetSDDCoreBlacklist returns the SDDCoreBlacklist field.
func (b *Beneficiary) GetSDDCoreBlacklist() []string {
	if b != nil {
		return b.SDDCoreBlacklist
	}
	return nil
}

// GetSDDCoreKnownUniqueMandateReference returns the SDDCoreKnownUniqueMandateReference field.
func (b *Beneficiary) GetSDDCoreKnownUniqueMandateReference() []string {
	if b != nil {
		return b.SDDCoreKnownUniqueMandateReference
	}
	return nil
}

// GetSepaCreditorIdentifier returns the SepaCreditorIdentifier field if it's non-nil, zero value otherwise.
func (b *Beneficiary) GetSepaCreditorIdentifier() string {
	if b != nil && b.SepaCreditorIdentifier != nil {
		return *b.SepaCreditorIdentifier
	}
	return ""
}

// GetTag returns the Tag field if it's non-nil, zero value otherwise.
func (b *Beneficiary) GetTag() string {
	if b != nil && b.Tag != nil {
		return *b.Tag
	}
	return ""
}

// GetAddress returns the Address field if it's non-nil, zero value otherwise.
func (b *BeneficiaryRequest) GetAddress() string {
	if b != nil && b.Address != nil {
		return *b.Address
	}
	return ""
}

// GetBeneficiaryID returns the BeneficiaryID field if it's non-nil, zero value otherwise.
func (b *BeneficiaryRequest) GetBeneficiaryID() string {
	if b != nil && b.BeneficiaryID != nil {
		return *b.BeneficiaryID
	}
	return ""
}

// GetBIC returns the BIC field if it's non-nil, zero value otherwise.
func (b *BeneficiaryRequest) GetBIC() string {
	if b != nil && b.BIC != nil {
		return *b.BIC
	}
	return ""
}

// GetIBAN returns the IBAN field if it's non-nil, zero value otherwise.
func (b *BeneficiaryRequest) GetIBAN() string {
	if b != nil && b.IBAN != nil {
		return *b.IBAN
	}
	return ""
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (b *BeneficiaryRequest) GetName() string {
	if b != nil && b.Name != nil {
		return *b.Name
	}
	return ""
}

// GetNickName returns the NickName field if it's non-nil, zero value otherwise.
func (b *BeneficiaryRequest) GetNickName() string {
	if b != nil && b.NickName != nil {
		return *b.NickName
	}
	return ""
}

// GetSDDB2BWhitelist returns the SDDB2BWhitelist field.
func (b *BeneficiaryRequest) GetSDDB2BWhitelist() []*SDDB2BWhitelist {
	if b != nil {
		return b.SDDB2BWhitelist
	}
	return nil
}

// GetSDDCoreBlacklist returns the SDDCoreBlacklist field if it's non-nil, zero value otherwise.
func (b *BeneficiaryRequest) GetSDDCoreBlacklist() []string {
	if b != nil && b.SDDCoreBlacklist != nil {
		return *b.SDDCoreBlacklist
	}
	return nil
}

// GetSDDCoreKnownUniqueMandateReference returns the SDDCoreKnownUniqueMandateReference field if it's non-nil, zero value otherwise.
func (b *BeneficiaryRequest) GetSDDCoreKnownUniqueMandateReference() []string {
	if b != nil && b.SDDCoreKnownUniqueMandateReference != nil {
		return *b.SDDCoreKnownUniqueMandateReference
	}
	return nil
}

// GetSEPACreditorIdentifier returns the SEPACreditorIdentifier field if it's non-nil, zero value otherwise.
func (b *BeneficiaryRequest) GetSEPACreditorIdentifier() string {
	if b != nil && b.SEPACreditorIdentifier != nil {
		return *b.SEPACreditorIdentifier
	}
	return ""
}

// GetTag returns the Tag field if it's non-nil, zero value otherwise.
func (b *BeneficiaryRequest) GetTag() string {
	if b != nil && b.Tag != nil {
		return *b.Tag
	}
	return ""
}

// GetUsableForSCT returns the UsableForSCT field if it's non-nil, zero value otherwise.
func (b *BeneficiaryRequest) GetUsableForSCT() bool {
	if b != nil && b.UsableForSCT != nil {
		return *b.UsableForSCT
	}
	return false
}

// GetUserID returns the UserID field if it's non-nil, zero value otherwise.
func (b *BeneficiaryRequest) GetUserID() string {
	if b != nil && b.UserID != nil {
		return *b.UserID
	}
	return ""
}

// GetBeneficiaries returns the Beneficiaries field.
func (b *BeneficiaryResponse) GetBeneficiaries() []*Beneficiary {
	if b != nil {
		return b.Beneficiaries
	}
	return nil
}

// GetCardDesign returns the CardDesign field if it's non-nil, zero value otherwise.
func (c *Card) GetCardDesign() string {
	if c != nil && c.CardDesign != nil {
		return *c.CardDesign
	}
	return ""
}

// GetCardTag returns the CardTag field if it's non-nil, zero value otherwise.
func (c *Card) GetCardTag() string {
	if c != nil && c.CardTag != nil {
		return *c.CardTag
	}
	return ""
}

// GetCountryCode returns the CountryCode field if it's non-nil, zero value otherwise.
func (c *Card) GetCountryCode() string {
	if c != nil && c.CountryCode != nil {
		return *c.CountryCode
	}
	return ""
}

// GetCVV returns the CVV field if it's non-nil, zero value otherwise.
func (c *Card) GetCVV() string {
	if c != nil && c.CVV != nil {
		return *c.CVV
	}
	return ""
}

// GetDeliveryAddress1 returns the DeliveryAddress1 field if it's non-nil, zero value otherwise.
func (c *Card) GetDeliveryAddress1() string {
	if c != nil && c.DeliveryAddress1 != nil {
		return *c.DeliveryAddress1
	}
	return ""
}

// GetDeliveryAddress2 returns the DeliveryAddress2 field if it's non-nil, zero value otherwise.
func (c *Card) GetDeliveryAddress2() string {
	if c != nil && c.DeliveryAddress2 != nil {
		return *c.DeliveryAddress2
	}
	return ""
}

// GetDeliveryAddress3 returns the DeliveryAddress3 field if it's non-nil, zero value otherwise.
func (c *Card) GetDeliveryAddress3() string {
	if c != nil && c.DeliveryAddress3 != nil {
		return *c.DeliveryAddress3
	}
	return ""
}

// GetDeliveryCity returns the DeliveryCity field if it's non-nil, zero value otherwise.
func (c *Card) GetDeliveryCity() string {
	if c != nil && c.DeliveryCity != nil {
		return *c.DeliveryCity
	}
	return ""
}

// GetDeliveryCountry returns the DeliveryCountry field if it's non-nil, zero value otherwise.
func (c *Card) GetDeliveryCountry() string {
	if c != nil && c.DeliveryCountry != nil {
		return *c.DeliveryCountry
	}
	return ""
}

// GetDeliveryFirstname returns the DeliveryFirstname field if it's non-nil, zero value otherwise.
func (c *Card) GetDeliveryFirstname() string {
	if c != nil && c.DeliveryFirstname != nil {
		return *c.DeliveryFirstname
	}
	return ""
}

// GetDeliveryLastname returns the DeliveryLastname field if it's non-nil, zero value otherwise.
func (c *Card) GetDeliveryLastname() string {
	if c != nil && c.DeliveryLastname != nil {
		return *c.DeliveryLastname
	}
	return ""
}

// GetDeliveryPostcode returns the DeliveryPostcode field if it's non-nil, zero value otherwise.
func (c *Card) GetDeliveryPostcode() string {
	if c != nil && c.DeliveryPostcode != nil {
		return *c.DeliveryPostcode
	}
	return ""
}

// GetDeliveryTitle returns the DeliveryTitle field if it's non-nil, zero value otherwise.
func (c *Card) GetDeliveryTitle() string {
	if c != nil && c.DeliveryTitle != nil {
		return *c.DeliveryTitle
	}
	return ""
}

// GetEmbossedName returns the EmbossedName field if it's non-nil, zero value otherwise.
func (c *Card) GetEmbossedName() string {
	if c != nil && c.EmbossedName != nil {
		return *c.EmbossedName
	}
	return ""
}

// GetEventAlias returns the EventAlias field if it's non-nil, zero value otherwise.
func (c *Card) GetEventAlias() string {
	if c != nil && c.EventAlias != nil {
		return *c.EventAlias
	}
	return ""
}

// GetEventName returns the EventName field if it's non-nil, zero value otherwise.
func (c *Card) GetEventName() string {
	if c != nil && c.EventName != nil {
		return *c.EventName
	}
	return ""
}

// GetLang returns the Lang field if it's non-nil, zero value otherwise.
func (c *Card) GetLang() string {
	if c != nil && c.Lang != nil {
		return *c.Lang
	}
	return ""
}

// GetLimitsGroup returns the LimitsGroup field if it's non-nil, zero value otherwise.
func (c *Card) GetLimitsGroup() string {
	if c != nil && c.LimitsGroup != nil {
		return *c.LimitsGroup
	}
	return ""
}

// GetMaskedPan returns the MaskedPan field if it's non-nil, zero value otherwise.
func (c *Card) GetMaskedPan() string {
	if c != nil && c.MaskedPan != nil {
		return *c.MaskedPan
	}
	return ""
}

// GetMobileSent returns the MobileSent field if it's non-nil, zero value otherwise.
func (c *Card) GetMobileSent() string {
	if c != nil && c.MobileSent != nil {
		return *c.MobileSent
	}
	return ""
}

// GetPermsGroup returns the PermsGroup field if it's non-nil, zero value otherwise.
func (c *Card) GetPermsGroup() string {
	if c != nil && c.PermsGroup != nil {
		return *c.PermsGroup
	}
	return ""
}

// GetPublicToken returns the PublicToken field if it's non-nil, zero value otherwise.
func (c *Card) GetPublicToken() string {
	if c != nil && c.PublicToken != nil {
		return *c.PublicToken
	}
	return ""
}

// GetRestrictionGroupLimits returns the RestrictionGroupLimits field.
func (c *Card) GetRestrictionGroupLimits() []*CardRestrictionGroupLimits {
	if c != nil {
		return c.RestrictionGroupLimits
	}
	return nil
}

// GetStatusCode returns the StatusCode field if it's non-nil, zero value otherwise.
func (c *Card) GetStatusCode() string {
	if c != nil && c.StatusCode != nil {
		return *c.StatusCode
	}
	return ""
}

// GetCardID returns the CardID field if it's non-nil, zero value otherwise.
func (c *Card3DS) GetCardID() string {
	if c != nil && c.CardID != nil {
		return *c.CardID
	}
	return ""
}

// GetCardID returns the CardID field if it's non-nil, zero value otherwise.
func (c *CardImage) GetCardID() string {
	if c != nil && c.CardID != nil {
		return *c.CardID
	}
	return ""
}

// GetFile returns the File field if it's non-nil, zero value otherwise.
func (c *CardImage) GetFile() string {
	if c != nil && c.File != nil {
		return *c.File
	}
	return ""
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (c *CardImage) GetID() string {
	if c != nil && c.ID != nil {
		return *c.ID
	}
	return ""
}

// GetCardImages returns the CardImages field.
func (c *CardImagesResponse) GetCardImages() []*CardImage {
	if c != nil {
		return c.CardImages
	}
	return nil
}

// GetLockStatus returns the LockStatus field if it's non-nil, zero value otherwise.
func (c *CardLockUnlockOptions) GetLockStatus() int64 {
	if c != nil && c.LockStatus != nil {
		return *c.LockStatus
	}
	return 0
}

// GetCards returns the Cards field.
func (c *CardResponse) GetCards() []*Card {
	if c != nil {
		return c.Cards
	}
	return nil
}

// GetCountryRestrictionGroups returns the CountryRestrictionGroups field if it's non-nil, zero value otherwise.
func (c *CardRestrictionGroupLimits) GetCountryRestrictionGroups() string {
	if c != nil && c.CountryRestrictionGroups != nil {
		return *c.CountryRestrictionGroups
	}
	return ""
}

// GetMccRestrictionGroups returns the MccRestrictionGroups field if it's non-nil, zero value otherwise.
func (c *CardRestrictionGroupLimits) GetMccRestrictionGroups() string {
	if c != nil && c.MccRestrictionGroups != nil {
		return *c.MccRestrictionGroups
	}
	return ""
}

// GetMerchantIdRestrictionGroups returns the MerchantIdRestrictionGroups field if it's non-nil, zero value otherwise.
func (c *CardRestrictionGroupLimits) GetMerchantIdRestrictionGroups() string {
	if c != nil && c.MerchantIdRestrictionGroups != nil {
		return *c.MerchantIdRestrictionGroups
	}
	return ""
}

// GetAuthorizationIssuerID returns the AuthorizationIssuerID field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetAuthorizationIssuerID() string {
	if c != nil && c.AuthorizationIssuerID != nil {
		return *c.AuthorizationIssuerID
	}
	return ""
}

// GetAuthorizationMTI returns the AuthorizationMTI field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetAuthorizationMTI() string {
	if c != nil && c.AuthorizationMTI != nil {
		return *c.AuthorizationMTI
	}
	return ""
}

// GetAuthorizationNote returns the AuthorizationNote field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetAuthorizationNote() string {
	if c != nil && c.AuthorizationNote != nil {
		return *c.AuthorizationNote
	}
	return ""
}

// GetAuthorizationResponseCode returns the AuthorizationResponseCode field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetAuthorizationResponseCode() string {
	if c != nil && c.AuthorizationResponseCode != nil {
		return *c.AuthorizationResponseCode
	}
	return ""
}

// GetMccCode returns the MccCode field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetMccCode() string {
	if c != nil && c.MccCode != nil {
		return *c.MccCode
	}
	return ""
}

// GetMerchantCity returns the MerchantCity field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetMerchantCity() string {
	if c != nil && c.MerchantCity != nil {
		return *c.MerchantCity
	}
	return ""
}

// GetMerchantCountry returns the MerchantCountry field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetMerchantCountry() string {
	if c != nil && c.MerchantCountry != nil {
		return *c.MerchantCountry
	}
	return ""
}

// GetMerchantID returns the MerchantID field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetMerchantID() string {
	if c != nil && c.MerchantID != nil {
		return *c.MerchantID
	}
	return ""
}

// GetMerchantName returns the MerchantName field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetMerchantName() string {
	if c != nil && c.MerchantName != nil {
		return *c.MerchantName
	}
	return ""
}

// GetPanEntryMethod returns the PanEntryMethod field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetPanEntryMethod() string {
	if c != nil && c.PanEntryMethod != nil {
		return *c.PanEntryMethod
	}
	return ""
}

// GetPaymentCountry returns the PaymentCountry field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetPaymentCountry() string {
	if c != nil && c.PaymentCountry != nil {
		return *c.PaymentCountry
	}
	return ""
}

// GetPaymentCurrency returns the PaymentCurrency field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetPaymentCurrency() string {
	if c != nil && c.PaymentCurrency != nil {
		return *c.PaymentCurrency
	}
	return ""
}

// GetPaymentStatus returns the PaymentStatus field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetPaymentStatus() string {
	if c != nil && c.PaymentStatus != nil {
		return *c.PaymentStatus
	}
	return ""
}

// GetPosCountry returns the PosCountry field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetPosCountry() string {
	if c != nil && c.PosCountry != nil {
		return *c.PosCountry
	}
	return ""
}

// GetPosPostcode returns the PosPostcode field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetPosPostcode() string {
	if c != nil && c.PosPostcode != nil {
		return *c.PosPostcode
	}
	return ""
}

// GetPosTerminalID returns the PosTerminalID field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetPosTerminalID() string {
	if c != nil && c.PosTerminalID != nil {
		return *c.PosTerminalID
	}
	return ""
}

// GetPublicToken returns the PublicToken field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetPublicToken() string {
	if c != nil && c.PublicToken != nil {
		return *c.PublicToken
	}
	return ""
}

// GetWalletCurrency returns the WalletCurrency field if it's non-nil, zero value otherwise.
func (c *CardTransaction) GetWalletCurrency() string {
	if c != nil && c.WalletCurrency != nil {
		return *c.WalletCurrency
	}
	return ""
}

// GetCardTransactions returns the CardTransactions field.
func (c *CardTransactionResponse) GetCardTransactions() []*CardTransaction {
	if c != nil {
		return c.CardTransactions
	}
	return nil
}

// GetCardPrint returns the CardPrint field if it's non-nil, zero value otherwise.
func (c *CreateVirtualCardOptions) GetCardPrint() string {
	if c != nil && c.CardPrint != nil {
		return *c.CardPrint
	}
	return ""
}

// GetLockStatus returns the LockStatus field if it's non-nil, zero value otherwise.
func (c *CreateVirtualCardOptions) GetLockStatus() int64 {
	if c != nil && c.LockStatus != nil {
		return *c.LockStatus
	}
	return 0
}

// GetPIN returns the PIN field if it's non-nil, zero value otherwise.
func (c *CreateVirtualCardOptions) GetPIN() string {
	if c != nil && c.PIN != nil {
		return *c.PIN
	}
	return ""
}

// GetDocumentStatus returns the DocumentStatus field if it's non-nil, zero value otherwise.
func (d *Document) GetDocumentStatus() string {
	if d != nil && d.DocumentStatus != nil {
		return *d.DocumentStatus
	}
	return ""
}

// GetDocumentTag returns the DocumentTag field if it's non-nil, zero value otherwise.
func (d *Document) GetDocumentTag() string {
	if d != nil && d.DocumentTag != nil {
		return *d.DocumentTag
	}
	return ""
}

// GetDocumentType returns the DocumentType field if it's non-nil, zero value otherwise.
func (d *Document) GetDocumentType() string {
	if d != nil && d.DocumentType != nil {
		return *d.DocumentType
	}
	return ""
}

// GetDocumentTypeID returns the DocumentTypeID field.
func (d *Document) GetDocumentTypeID() *DocumentType {
	if d != nil {
		return d.DocumentTypeID
	}
	return nil
}

// GetFilename returns the Filename field if it's non-nil, zero value otherwise.
func (d *Document) GetFilename() string {
	if d != nil && d.Filename != nil {
		return *d.Filename
	}
	return ""
}

// GetInformationStatus returns the InformationStatus field if it's non-nil, zero value otherwise.
func (d *Document) GetInformationStatus() string {
	if d != nil && d.InformationStatus != nil {
		return *d.InformationStatus
	}
	return ""
}

// GetTemporaryURL returns the TemporaryURL field if it's non-nil, zero value otherwise.
func (d *Document) GetTemporaryURL() string {
	if d != nil && d.TemporaryURL != nil {
		return *d.TemporaryURL
	}
	return ""
}

// GetTemporaryURLThumb returns the TemporaryURLThumb field if it's non-nil, zero value otherwise.
func (d *Document) GetTemporaryURLThumb() string {
	if d != nil && d.TemporaryURLThumb != nil {
		return *d.TemporaryURLThumb
	}
	return ""
}

// GetUserFirstname returns the UserFirstname field if it's non-nil, zero value otherwise.
func (d *Document) GetUserFirstname() string {
	if d != nil && d.UserFirstname != nil {
		return *d.UserFirstname
	}
	return ""
}

// GetUserLastname returns the UserLastname field if it's non-nil, zero value otherwise.
func (d *Document) GetUserLastname() string {
	if d != nil && d.UserLastname != nil {
		return *d.UserLastname
	}
	return ""
}

// GetDocuments returns the Documents field.
func (d *DocumentResponse) GetDocuments() []*Document {
	if d != nil {
		return d.Documents
	}
	return nil
}

// GetFileContentBase64 returns the FileContentBase64 field if it's non-nil, zero value otherwise.
func (d *DocumentSendOptions) GetFileContentBase64() string {
	if d != nil && d.FileContentBase64 != nil {
		return *d.FileContentBase64
	}
	return ""
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (d *DocumentSendOptions) GetName() string {
	if d != nil && d.Name != nil {
		return *d.Name
	}
	return ""
}

// GetErrors returns the Errors field.
func (e *ErrorResponse) GetErrors() []Error {
	if e != nil {
		return e.Errors
	}
	return nil
}

// GetResponse returns the Response field if it's non-nil, zero value otherwise.
func (e *ErrorResponse) GetResponse() http.Response {
	if e != nil && e.Response != nil {
		return *e.Response
	}
	return http.Response{}
}

// GetIdentificationID returns the IdentificationID field if it's non-nil, zero value otherwise.
func (i *Identification) GetIdentificationID() string {
	if i != nil && i.IdentificationID != nil {
		return *i.IdentificationID
	}
	return ""
}

// GetIdentificationURL returns the IdentificationURL field if it's non-nil, zero value otherwise.
func (i *Identification) GetIdentificationURL() string {
	if i != nil && i.IdentificationURL != nil {
		return *i.IdentificationURL
	}
	return ""
}

// GetIdentification returns the Identification field.
func (i *IdentificationResponse) GetIdentification() *Identification {
	if i != nil {
		return i.Identification
	}
	return nil
}

// GetAdditionalData returns the AdditionalData field.
func (p *Payin) GetAdditionalData() *PayinAdditionalData {
	if p != nil {
		return p.AdditionalData
	}
	return nil
}

// GetCreatedIP returns the CreatedIP field if it's non-nil, zero value otherwise.
func (p *Payin) GetCreatedIP() string {
	if p != nil && p.CreatedIP != nil {
		return *p.CreatedIP
	}
	return ""
}

// GetCreditorAddressLine returns the CreditorAddressLine field if it's non-nil, zero value otherwise.
func (p *Payin) GetCreditorAddressLine() string {
	if p != nil && p.CreditorAddressLine != nil {
		return *p.CreditorAddressLine
	}
	return ""
}

// GetCreditorBIC returns the CreditorBIC field if it's non-nil, zero value otherwise.
func (p *Payin) GetCreditorBIC() string {
	if p != nil && p.CreditorBIC != nil {
		return *p.CreditorBIC
	}
	return ""
}

// GetCreditorCountry returns the CreditorCountry field if it's non-nil, zero value otherwise.
func (p *Payin) GetCreditorCountry() string {
	if p != nil && p.CreditorCountry != nil {
		return *p.CreditorCountry
	}
	return ""
}

// GetCreditorIBAN returns the CreditorIBAN field if it's non-nil, zero value otherwise.
func (p *Payin) GetCreditorIBAN() string {
	if p != nil && p.CreditorIBAN != nil {
		return *p.CreditorIBAN
	}
	return ""
}

// GetCreditorName returns the CreditorName field if it's non-nil, zero value otherwise.
func (p *Payin) GetCreditorName() string {
	if p != nil && p.CreditorName != nil {
		return *p.CreditorName
	}
	return ""
}

// GetDbtrIBAN returns the DbtrIBAN field if it's non-nil, zero value otherwise.
func (p *Payin) GetDbtrIBAN() string {
	if p != nil && p.DbtrIBAN != nil {
		return *p.DbtrIBAN
	}
	return ""
}

// GetForwardURL returns the ForwardURL field if it's non-nil, zero value otherwise.
func (p *Payin) GetForwardURL() string {
	if p != nil && p.ForwardURL != nil {
		return *p.ForwardURL
	}
	return ""
}

// GetIBANBIC returns the IBANBIC field if it's non-nil, zero value otherwise.
func (p *Payin) GetIBANBIC() string {
	if p != nil && p.IBANBIC != nil {
		return *p.IBANBIC
	}
	return ""
}

// GetIBANFullname returns the IBANFullname field if it's non-nil, zero value otherwise.
func (p *Payin) GetIBANFullname() string {
	if p != nil && p.IBANFullname != nil {
		return *p.IBANFullname
	}
	return ""
}

// GetIBANID returns the IBANID field if it's non-nil, zero value otherwise.
func (p *Payin) GetIBANID() string {
	if p != nil && p.IBANID != nil {
		return *p.IBANID
	}
	return ""
}

// GetIBANTxEndToEndID returns the IBANTxEndToEndID field if it's non-nil, zero value otherwise.
func (p *Payin) GetIBANTxEndToEndID() string {
	if p != nil && p.IBANTxEndToEndID != nil {
		return *p.IBANTxEndToEndID
	}
	return ""
}

// GetIBANTxID returns the IBANTxID field if it's non-nil, zero value otherwise.
func (p *Payin) GetIBANTxID() string {
	if p != nil && p.IBANTxID != nil {
		return *p.IBANTxID
	}
	return ""
}

// GetInformationStatus returns the InformationStatus field if it's non-nil, zero value otherwise.
func (p *Payin) GetInformationStatus() string {
	if p != nil && p.InformationStatus != nil {
		return *p.InformationStatus
	}
	return ""
}

// GetMessageToUser returns the MessageToUser field if it's non-nil, zero value otherwise.
func (p *Payin) GetMessageToUser() string {
	if p != nil && p.MessageToUser != nil {
		return *p.MessageToUser
	}
	return ""
}

// GetPayinStatus returns the PayinStatus field if it's non-nil, zero value otherwise.
func (p *Payin) GetPayinStatus() string {
	if p != nil && p.PayinStatus != nil {
		return *p.PayinStatus
	}
	return ""
}

// GetPayinTag returns the PayinTag field if it's non-nil, zero value otherwise.
func (p *Payin) GetPayinTag() string {
	if p != nil && p.PayinTag != nil {
		return *p.PayinTag
	}
	return ""
}

// GetPaymentAcceptedURL returns the PaymentAcceptedURL field if it's non-nil, zero value otherwise.
func (p *Payin) GetPaymentAcceptedURL() string {
	if p != nil && p.PaymentAcceptedURL != nil {
		return *p.PaymentAcceptedURL
	}
	return ""
}

// GetPaymentCanceledURL returns the PaymentCanceledURL field if it's non-nil, zero value otherwise.
func (p *Payin) GetPaymentCanceledURL() string {
	if p != nil && p.PaymentCanceledURL != nil {
		return *p.PaymentCanceledURL
	}
	return ""
}

// GetPaymentExceptionURL returns the PaymentExceptionURL field if it's non-nil, zero value otherwise.
func (p *Payin) GetPaymentExceptionURL() string {
	if p != nil && p.PaymentExceptionURL != nil {
		return *p.PaymentExceptionURL
	}
	return ""
}

// GetPaymentHTML returns the PaymentHTML field if it's non-nil, zero value otherwise.
func (p *Payin) GetPaymentHTML() string {
	if p != nil && p.PaymentHTML != nil {
		return *p.PaymentHTML
	}
	return ""
}

// GetPaymentLanguage returns the PaymentLanguage field if it's non-nil, zero value otherwise.
func (p *Payin) GetPaymentLanguage() string {
	if p != nil && p.PaymentLanguage != nil {
		return *p.PaymentLanguage
	}
	return ""
}

// GetPaymentPostDataURL returns the PaymentPostDataURL field if it's non-nil, zero value otherwise.
func (p *Payin) GetPaymentPostDataURL() string {
	if p != nil && p.PaymentPostDataURL != nil {
		return *p.PaymentPostDataURL
	}
	return ""
}

// GetPaymentPostURL returns the PaymentPostURL field if it's non-nil, zero value otherwise.
func (p *Payin) GetPaymentPostURL() string {
	if p != nil && p.PaymentPostURL != nil {
		return *p.PaymentPostURL
	}
	return ""
}

// GetPaymentRefusedURL returns the PaymentRefusedURL field if it's non-nil, zero value otherwise.
func (p *Payin) GetPaymentRefusedURL() string {
	if p != nil && p.PaymentRefusedURL != nil {
		return *p.PaymentRefusedURL
	}
	return ""
}

// GetPaymentWaitingURL returns the PaymentWaitingURL field if it's non-nil, zero value otherwise.
func (p *Payin) GetPaymentWaitingURL() string {
	if p != nil && p.PaymentWaitingURL != nil {
		return *p.PaymentWaitingURL
	}
	return ""
}

// GetUserFirstname returns the UserFirstname field if it's non-nil, zero value otherwise.
func (p *Payin) GetUserFirstname() string {
	if p != nil && p.UserFirstname != nil {
		return *p.UserFirstname
	}
	return ""
}

// GetUserLastname returns the UserLastname field if it's non-nil, zero value otherwise.
func (p *Payin) GetUserLastname() string {
	if p != nil && p.UserLastname != nil {
		return *p.UserLastname
	}
	return ""
}

// GetVirtualIBANReference returns the VirtualIBANReference field if it's non-nil, zero value otherwise.
func (p *Payin) GetVirtualIBANReference() string {
	if p != nil && p.VirtualIBANReference != nil {
		return *p.VirtualIBANReference
	}
	return ""
}

// GetWalletAlias returns the WalletAlias field if it's non-nil, zero value otherwise.
func (p *Payin) GetWalletAlias() string {
	if p != nil && p.WalletAlias != nil {
		return *p.WalletAlias
	}
	return ""
}

// GetWalletEventName returns the WalletEventName field if it's non-nil, zero value otherwise.
func (p *Payin) GetWalletEventName() string {
	if p != nil && p.WalletEventName != nil {
		return *p.WalletEventName
	}
	return ""
}

// GetPayins returns the Payins field.
func (p *PayinResponse) GetPayins() []*Payin {
	if p != nil {
		return p.Payins
	}
	return nil
}

// GetBankAccountIBAN returns the BankAccountIBAN field if it's non-nil, zero value otherwise.
func (p *Payout) GetBankAccountIBAN() string {
	if p != nil && p.BankAccountIBAN != nil {
		return *p.BankAccountIBAN
	}
	return ""
}

// GetInformationStatus returns the InformationStatus field if it's non-nil, zero value otherwise.
func (p *Payout) GetInformationStatus() string {
	if p != nil && p.InformationStatus != nil {
		return *p.InformationStatus
	}
	return ""
}

// GetLabel returns the Label field if it's non-nil, zero value otherwise.
func (p *Payout) GetLabel() string {
	if p != nil && p.Label != nil {
		return *p.Label
	}
	return ""
}

// GetPayoutStatus returns the PayoutStatus field if it's non-nil, zero value otherwise.
func (p *Payout) GetPayoutStatus() string {
	if p != nil && p.PayoutStatus != nil {
		return *p.PayoutStatus
	}
	return ""
}

// GetPayoutTag returns the PayoutTag field if it's non-nil, zero value otherwise.
func (p *Payout) GetPayoutTag() string {
	if p != nil && p.PayoutTag != nil {
		return *p.PayoutTag
	}
	return ""
}

// GetPayoutType returns the PayoutType field if it's non-nil, zero value otherwise.
func (p *Payout) GetPayoutType() string {
	if p != nil && p.PayoutType != nil {
		return *p.PayoutType
	}
	return ""
}

// GetPayoutTypeID returns the PayoutTypeID field.
func (p *Payout) GetPayoutTypeID() *PayoutType {
	if p != nil {
		return p.PayoutTypeID
	}
	return nil
}

// GetUniqueMandateReference returns the UniqueMandateReference field if it's non-nil, zero value otherwise.
func (p *Payout) GetUniqueMandateReference() string {
	if p != nil && p.UniqueMandateReference != nil {
		return *p.UniqueMandateReference
	}
	return ""
}

// GetUserFirstname returns the UserFirstname field if it's non-nil, zero value otherwise.
func (p *Payout) GetUserFirstname() string {
	if p != nil && p.UserFirstname != nil {
		return *p.UserFirstname
	}
	return ""
}

// GetUserLastname returns the UserLastname field if it's non-nil, zero value otherwise.
func (p *Payout) GetUserLastname() string {
	if p != nil && p.UserLastname != nil {
		return *p.UserLastname
	}
	return ""
}

// GetWalletAlias returns the WalletAlias field if it's non-nil, zero value otherwise.
func (p *Payout) GetWalletAlias() string {
	if p != nil && p.WalletAlias != nil {
		return *p.WalletAlias
	}
	return ""
}

// GetWalletEventName returns the WalletEventName field if it's non-nil, zero value otherwise.
func (p *Payout) GetWalletEventName() string {
	if p != nil && p.WalletEventName != nil {
		return *p.WalletEventName
	}
	return ""
}

// GetPayouts returns the Payouts field.
func (p *PayoutResponse) GetPayouts() []*Payout {
	if p != nil {
		return p.Payouts
	}
	return nil
}

// GetCountryRestrictionGroups returns the CountryRestrictionGroups field if it's non-nil, zero value otherwise.
func (r *RestrictionGroupLimits) GetCountryRestrictionGroups() json.Number {
	if r != nil && r.CountryRestrictionGroups != nil {
		return *r.CountryRestrictionGroups
	}
	return json.Number("")
}

// GetMccRestrictionGroups returns the MccRestrictionGroups field if it's non-nil, zero value otherwise.
func (r *RestrictionGroupLimits) GetMccRestrictionGroups() json.Number {
	if r != nil && r.MccRestrictionGroups != nil {
		return *r.MccRestrictionGroups
	}
	return json.Number("")
}

// GetMerchantIdRestrictionGroups returns the MerchantIdRestrictionGroups field if it's non-nil, zero value otherwise.
func (r *RestrictionGroupLimits) GetMerchantIdRestrictionGroups() json.Number {
	if r != nil && r.MerchantIdRestrictionGroups != nil {
		return *r.MerchantIdRestrictionGroups
	}
	return json.Number("")
}

// GetPaymentDailyLimit returns the PaymentDailyLimit field if it's non-nil, zero value otherwise.
func (r *RestrictionGroupLimits) GetPaymentDailyLimit() json.Number {
	if r != nil && r.PaymentDailyLimit != nil {
		return *r.PaymentDailyLimit
	}
	return json.Number("")
}

// GetUniqueMandateReference returns the UniqueMandateReference field if it's non-nil, zero value otherwise.
func (s *SDDB2BWhitelist) GetUniqueMandateReference() string {
	if s != nil && s.UniqueMandateReference != nil {
		return *s.UniqueMandateReference
	}
	return ""
}

// GetCountry returns the Country field if it's non-nil, zero value otherwise.
func (t *TaxResidence) GetCountry() string {
	if t != nil && t.Country != nil {
		return *t.Country
	}
	return ""
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (t *TaxResidence) GetID() int64 {
	if t != nil && t.ID != nil {
		return *t.ID
	}
	return 0
}

// GetLiabilityWaiver returns the LiabilityWaiver field if it's non-nil, zero value otherwise.
func (t *TaxResidence) GetLiabilityWaiver() bool {
	if t != nil && t.LiabilityWaiver != nil {
		return *t.LiabilityWaiver
	}
	return false
}

// GetTaxPayerID returns the TaxPayerID field if it's non-nil, zero value otherwise.
func (t *TaxResidence) GetTaxPayerID() string {
	if t != nil && t.TaxPayerID != nil {
		return *t.TaxPayerID
	}
	return ""
}

// GetUserID returns the UserID field if it's non-nil, zero value otherwise.
func (t *TaxResidence) GetUserID() int64 {
	if t != nil && t.UserID != nil {
		return *t.UserID
	}
	return 0
}

// GetTaxResidences returns the TaxResidences field.
func (t *TaxResidencesResponse) GetTaxResidences() []*TaxResidence {
	if t != nil {
		return t.TaxResidences
	}
	return nil
}

// GetBeneficiaryWalletAlias returns the BeneficiaryWalletAlias field if it's non-nil, zero value otherwise.
func (t *Transfer) GetBeneficiaryWalletAlias() string {
	if t != nil && t.BeneficiaryWalletAlias != nil {
		return *t.BeneficiaryWalletAlias
	}
	return ""
}

// GetBeneficiaryWalletEventName returns the BeneficiaryWalletEventName field if it's non-nil, zero value otherwise.
func (t *Transfer) GetBeneficiaryWalletEventName() string {
	if t != nil && t.BeneficiaryWalletEventName != nil {
		return *t.BeneficiaryWalletEventName
	}
	return ""
}

// GetInformationStatus returns the InformationStatus field if it's non-nil, zero value otherwise.
func (t *Transfer) GetInformationStatus() string {
	if t != nil && t.InformationStatus != nil {
		return *t.InformationStatus
	}
	return ""
}

// GetLabel returns the Label field if it's non-nil, zero value otherwise.
func (t *Transfer) GetLabel() string {
	if t != nil && t.Label != nil {
		return *t.Label
	}
	return ""
}

// GetTransferStatus returns the TransferStatus field if it's non-nil, zero value otherwise.
func (t *Transfer) GetTransferStatus() string {
	if t != nil && t.TransferStatus != nil {
		return *t.TransferStatus
	}
	return ""
}

// GetTransferTag returns the TransferTag field if it's non-nil, zero value otherwise.
func (t *Transfer) GetTransferTag() string {
	if t != nil && t.TransferTag != nil {
		return *t.TransferTag
	}
	return ""
}

// GetTransferTypeID returns the TransferTypeID field.
func (t *Transfer) GetTransferTypeID() *TransferType {
	if t != nil {
		return t.TransferTypeID
	}
	return nil
}

// GetWalletAlias returns the WalletAlias field if it's non-nil, zero value otherwise.
func (t *Transfer) GetWalletAlias() string {
	if t != nil && t.WalletAlias != nil {
		return *t.WalletAlias
	}
	return ""
}

// GetWalletEventName returns the WalletEventName field if it's non-nil, zero value otherwise.
func (t *Transfer) GetWalletEventName() string {
	if t != nil && t.WalletEventName != nil {
		return *t.WalletEventName
	}
	return ""
}

// GetTransfers returns the Transfers field.
func (t *TransferResponse) GetTransfers() []*Transfer {
	if t != nil {
		return t.Transfers
	}
	return nil
}

// GetAddress1 returns the Address1 field if it's non-nil, zero value otherwise.
func (u *User) GetAddress1() string {
	if u != nil && u.Address1 != nil {
		return *u.Address1
	}
	return ""
}

// GetAddress2 returns the Address2 field if it's non-nil, zero value otherwise.
func (u *User) GetAddress2() string {
	if u != nil && u.Address2 != nil {
		return *u.Address2
	}
	return ""
}

// GetAddress3 returns the Address3 field if it's non-nil, zero value otherwise.
func (u *User) GetAddress3() string {
	if u != nil && u.Address3 != nil {
		return *u.Address3
	}
	return ""
}

// GetBirthCountry returns the BirthCountry field if it's non-nil, zero value otherwise.
func (u *User) GetBirthCountry() string {
	if u != nil && u.BirthCountry != nil {
		return *u.BirthCountry
	}
	return ""
}

// GetCity returns the City field if it's non-nil, zero value otherwise.
func (u *User) GetCity() string {
	if u != nil && u.City != nil {
		return *u.City
	}
	return ""
}

// GetCountry returns the Country field if it's non-nil, zero value otherwise.
func (u *User) GetCountry() string {
	if u != nil && u.Country != nil {
		return *u.Country
	}
	return ""
}

// GetCountryName returns the CountryName field if it's non-nil, zero value otherwise.
func (u *User) GetCountryName() string {
	if u != nil && u.CountryName != nil {
		return *u.CountryName
	}
	return ""
}

// GetEmail returns the Email field if it's non-nil, zero value otherwise.
func (u *User) GetEmail() string {
	if u != nil && u.Email != nil {
		return *u.Email
	}
	return ""
}

// GetFirstname returns the Firstname field if it's non-nil, zero value otherwise.
func (u *User) GetFirstname() string {
	if u != nil && u.Firstname != nil {
		return *u.Firstname
	}
	return ""
}

// GetIncomeRange returns the IncomeRange field if it's non-nil, zero value otherwise.
func (u *User) GetIncomeRange() string {
	if u != nil && u.IncomeRange != nil {
		return *u.IncomeRange
	}
	return ""
}

// GetInformationStatus returns the InformationStatus field if it's non-nil, zero value otherwise.
func (u *User) GetInformationStatus() string {
	if u != nil && u.InformationStatus != nil {
		return *u.InformationStatus
	}
	return ""
}

// GetKycReviewComment returns the KycReviewComment field if it's non-nil, zero value otherwise.
func (u *User) GetKycReviewComment() string {
	if u != nil && u.KycReviewComment != nil {
		return *u.KycReviewComment
	}
	return ""
}

// GetLanguage returns the Language field if it's non-nil, zero value otherwise.
func (u *User) GetLanguage() string {
	if u != nil && u.Language != nil {
		return *u.Language
	}
	return ""
}

// GetLastname returns the Lastname field if it's non-nil, zero value otherwise.
func (u *User) GetLastname() string {
	if u != nil && u.Lastname != nil {
		return *u.Lastname
	}
	return ""
}

// GetLegalAnnualTurnOver returns the LegalAnnualTurnOver field if it's non-nil, zero value otherwise.
func (u *User) GetLegalAnnualTurnOver() string {
	if u != nil && u.LegalAnnualTurnOver != nil {
		return *u.LegalAnnualTurnOver
	}
	return ""
}

// GetLegalForm returns the LegalForm field if it's non-nil, zero value otherwise.
func (u *User) GetLegalForm() string {
	if u != nil && u.LegalForm != nil {
		return *u.LegalForm
	}
	return ""
}

// GetLegalName returns the LegalName field if it's non-nil, zero value otherwise.
func (u *User) GetLegalName() string {
	if u != nil && u.LegalName != nil {
		return *u.LegalName
	}
	return ""
}

// GetLegalNameEmbossed returns the LegalNameEmbossed field if it's non-nil, zero value otherwise.
func (u *User) GetLegalNameEmbossed() string {
	if u != nil && u.LegalNameEmbossed != nil {
		return *u.LegalNameEmbossed
	}
	return ""
}

// GetLegalNetIncomeRange returns the LegalNetIncomeRange field if it's non-nil, zero value otherwise.
func (u *User) GetLegalNetIncomeRange() string {
	if u != nil && u.LegalNetIncomeRange != nil {
		return *u.LegalNetIncomeRange
	}
	return ""
}

// GetLegalNumberOfEmployeeRange returns the LegalNumberOfEmployeeRange field if it's non-nil, zero value otherwise.
func (u *User) GetLegalNumberOfEmployeeRange() string {
	if u != nil && u.LegalNumberOfEmployeeRange != nil {
		return *u.LegalNumberOfEmployeeRange
	}
	return ""
}

// GetLegalRegistrationNumber returns the LegalRegistrationNumber field if it's non-nil, zero value otherwise.
func (u *User) GetLegalRegistrationNumber() string {
	if u != nil && u.LegalRegistrationNumber != nil {
		return *u.LegalRegistrationNumber
	}
	return ""
}

// GetLegalSector returns the LegalSector field if it's non-nil, zero value otherwise.
func (u *User) GetLegalSector() string {
	if u != nil && u.LegalSector != nil {
		return *u.LegalSector
	}
	return ""
}

// GetLegalTvaNumber returns the LegalTvaNumber field if it's non-nil, zero value otherwise.
func (u *User) GetLegalTvaNumber() string {
	if u != nil && u.LegalTvaNumber != nil {
		return *u.LegalTvaNumber
	}
	return ""
}

// GetMiddleNames returns the MiddleNames field if it's non-nil, zero value otherwise.
func (u *User) GetMiddleNames() string {
	if u != nil && u.MiddleNames != nil {
		return *u.MiddleNames
	}
	return ""
}

// GetMobile returns the Mobile field if it's non-nil, zero value otherwise.
func (u *User) GetMobile() string {
	if u != nil && u.Mobile != nil {
		return *u.Mobile
	}
	return ""
}

// GetNationality returns the Nationality field if it's non-nil, zero value otherwise.
func (u *User) GetNationality() string {
	if u != nil && u.Nationality != nil {
		return *u.Nationality
	}
	return ""
}

// GetNationalityOther returns the NationalityOther field if it's non-nil, zero value otherwise.
func (u *User) GetNationalityOther() string {
	if u != nil && u.NationalityOther != nil {
		return *u.NationalityOther
	}
	return ""
}

// GetOccupation returns the Occupation field if it's non-nil, zero value otherwise.
func (u *User) GetOccupation() string {
	if u != nil && u.Occupation != nil {
		return *u.Occupation
	}
	return ""
}

// GetParentType returns the ParentType field if it's non-nil, zero value otherwise.
func (u *User) GetParentType() string {
	if u != nil && u.ParentType != nil {
		return *u.ParentType
	}
	return ""
}

// GetPersonalAssets returns the PersonalAssets field if it's non-nil, zero value otherwise.
func (u *User) GetPersonalAssets() string {
	if u != nil && u.PersonalAssets != nil {
		return *u.PersonalAssets
	}
	return ""
}

// GetPhone returns the Phone field if it's non-nil, zero value otherwise.
func (u *User) GetPhone() string {
	if u != nil && u.Phone != nil {
		return *u.Phone
	}
	return ""
}

// GetPlaceOfBirth returns the PlaceOfBirth field if it's non-nil, zero value otherwise.
func (u *User) GetPlaceOfBirth() string {
	if u != nil && u.PlaceOfBirth != nil {
		return *u.PlaceOfBirth
	}
	return ""
}

// GetPosition returns the Position field if it's non-nil, zero value otherwise.
func (u *User) GetPosition() string {
	if u != nil && u.Position != nil {
		return *u.Position
	}
	return ""
}

// GetPostcode returns the Postcode field if it's non-nil, zero value otherwise.
func (u *User) GetPostcode() string {
	if u != nil && u.Postcode != nil {
		return *u.Postcode
	}
	return ""
}

// GetSepaCreditorIdentifier returns the SepaCreditorIdentifier field if it's non-nil, zero value otherwise.
func (u *User) GetSepaCreditorIdentifier() string {
	if u != nil && u.SepaCreditorIdentifier != nil {
		return *u.SepaCreditorIdentifier
	}
	return ""
}

// GetState returns the State field if it's non-nil, zero value otherwise.
func (u *User) GetState() string {
	if u != nil && u.State != nil {
		return *u.State
	}
	return ""
}

// GetTaxNumber returns the TaxNumber field if it's non-nil, zero value otherwise.
func (u *User) GetTaxNumber() string {
	if u != nil && u.TaxNumber != nil {
		return *u.TaxNumber
	}
	return ""
}

// GetTaxResidence returns the TaxResidence field if it's non-nil, zero value otherwise.
func (u *User) GetTaxResidence() string {
	if u != nil && u.TaxResidence != nil {
		return *u.TaxResidence
	}
	return ""
}

// GetTimezone returns the Timezone field if it's non-nil, zero value otherwise.
func (u *User) GetTimezone() string {
	if u != nil && u.Timezone != nil {
		return *u.Timezone
	}
	return ""
}

// GetTitle returns the Title field if it's non-nil, zero value otherwise.
func (u *User) GetTitle() string {
	if u != nil && u.Title != nil {
		return *u.Title
	}
	return ""
}

// GetUserStatus returns the UserStatus field if it's non-nil, zero value otherwise.
func (u *User) GetUserStatus() string {
	if u != nil && u.UserStatus != nil {
		return *u.UserStatus
	}
	return ""
}

// GetUserTag returns the UserTag field if it's non-nil, zero value otherwise.
func (u *User) GetUserTag() string {
	if u != nil && u.UserTag != nil {
		return *u.UserTag
	}
	return ""
}

// GetUsers returns the Users field.
func (u *UserResponse) GetUsers() []*User {
	if u != nil {
		return u.Users
	}
	return nil
}

// GetBIC returns the BIC field if it's non-nil, zero value otherwise.
func (w *Wallet) GetBIC() string {
	if w != nil && w.BIC != nil {
		return *w.BIC
	}
	return ""
}

// GetEventAlias returns the EventAlias field if it's non-nil, zero value otherwise.
func (w *Wallet) GetEventAlias() string {
	if w != nil && w.EventAlias != nil {
		return *w.EventAlias
	}
	return ""
}

// GetEventMessage returns the EventMessage field if it's non-nil, zero value otherwise.
func (w *Wallet) GetEventMessage() string {
	if w != nil && w.EventMessage != nil {
		return *w.EventMessage
	}
	return ""
}

// GetEventName returns the EventName field if it's non-nil, zero value otherwise.
func (w *Wallet) GetEventName() string {
	if w != nil && w.EventName != nil {
		return *w.EventName
	}
	return ""
}

// GetIBAN returns the IBAN field if it's non-nil, zero value otherwise.
func (w *Wallet) GetIBAN() string {
	if w != nil && w.IBAN != nil {
		return *w.IBAN
	}
	return ""
}

// GetInformationStatus returns the InformationStatus field if it's non-nil, zero value otherwise.
func (w *Wallet) GetInformationStatus() string {
	if w != nil && w.InformationStatus != nil {
		return *w.InformationStatus
	}
	return ""
}

// GetURLImage returns the URLImage field if it's non-nil, zero value otherwise.
func (w *Wallet) GetURLImage() string {
	if w != nil && w.URLImage != nil {
		return *w.URLImage
	}
	return ""
}

// GetUserFirstname returns the UserFirstname field if it's non-nil, zero value otherwise.
func (w *Wallet) GetUserFirstname() string {
	if w != nil && w.UserFirstname != nil {
		return *w.UserFirstname
	}
	return ""
}

// GetUserLastname returns the UserLastname field if it's non-nil, zero value otherwise.
func (w *Wallet) GetUserLastname() string {
	if w != nil && w.UserLastname != nil {
		return *w.UserLastname
	}
	return ""
}

// GetWalletStatus returns the WalletStatus field if it's non-nil, zero value otherwise.
func (w *Wallet) GetWalletStatus() string {
	if w != nil && w.WalletStatus != nil {
		return *w.WalletStatus
	}
	return ""
}

// GetWalletTag returns the WalletTag field if it's non-nil, zero value otherwise.
func (w *Wallet) GetWalletTag() string {
	if w != nil && w.WalletTag != nil {
		return *w.WalletTag
	}
	return ""
}

// GetWallets returns the Wallets field.
func (w *WalletResponse) GetWallets() []*Wallet {
	if w != nil {
		return w.Wallets
	}
	return nil
}
